# Generated by Django 5.0.4 on 2024-11-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=10, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="team_logos/"),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "coach",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"role": "Coach"},
                        related_name="teams_coached",
                        to="accounts.wajouser",
                    ),
                ),
            ],
        ),
    ]
