# Generated by Django 5.0.10 on 2026-01-06 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='team_logos/')),
                ('jersey_color', models.CharField(blank=True, max_length=7, null=True)),
                ('language_metadata', models.JSONField(blank=True, default=dict, help_text="Multilingual team names: {'en': 'Team Name', 'he': 'שם הקבוצה'}", null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('coach', models.ManyToManyField(blank=True, limit_choices_to={'role': 'Coach'}, related_name='teams_coached', to='accounts.wajouser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metrics', models.JSONField(default=dict)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_team_stats', to='games.game')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_stats', to='teams.team')),
            ],
            options={
                'verbose_name': 'Team Stats',
                'verbose_name_plural': 'Team Stats',
                'unique_together': {('team', 'game')},
            },
        ),
    ]
