# Generated by Django 5.0.4 on 2024-11-28 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0003_gamegpsdata_game_type_gamevideodata_game_type"),
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metrics", models.JSONField(default=dict)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_team_stats",
                        to="games.game",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_stats",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Team Stats",
                "verbose_name_plural": "Team Stats",
                "unique_together": {("team", "game")},
            },
        ),
    ]
