# Generated by Django 5.0.10 on 2024-12-12 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_teamstats"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teamstats",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
