# Generated by Django 5.0.10 on 2025-08-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_deleted_at_teamstats_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='jersey_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
