# Generated by Django 5.0.10 on 2025-12-23 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_team_language_names'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='language_names',
            new_name='language_metadata',
        ),
    ]
