# Generated by Django 5.0.10 on 2025-12-30 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_rename_language_names_team_language_metadata'),
    ]

    operations = [
    ]
