# Generated by Django 5.0.10 on 2026-01-06 12:37

import django.db.models.deletion
import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchEventsDataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('_type', models.CharField(choices=[('BEPRO', 'BEPRO'), ('GPS', 'GPS')], default='BEPRO', max_length=10)),
                ('file', models.FileField(upload_to=events.models.match_events_data_file_path, validators=[events.models.validate_file_extension])),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Match Events Data File',
                'verbose_name_plural': 'Match Events Data Files',
            },
        ),
        migrations.CreateModel(
            name='OneTimeEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('event_type', models.CharField(blank=True, max_length=50, null=True)),
                ('event', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=150, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_time_events', to='accounts.wajouser')),
            ],
            options={
                'verbose_name': 'One Time Event',
                'verbose_name_plural': 'One Time Events',
            },
        ),
        migrations.CreateModel(
            name='RecurringEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('event_type', models.CharField(blank=True, max_length=50, null=True)),
                ('event', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=150, null=True)),
                ('frequency', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], default='Daily', max_length=15)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_events', to='accounts.wajouser')),
            ],
            options={
                'verbose_name': 'Recurring Event',
                'verbose_name_plural': 'Recurring Events',
            },
        ),
    ]
