# Generated by Django 5.0.10 on 2025-12-30 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_matcheventsdatafile_deleted_at_and_more'),
    ]

    operations = [
    ]
