version: '3.8'

services:
  pilot_wajo_backend:
    build: .
    command: >
      bash -c "
              python manage.py makemigrations && 
              python manage.py migrate && 
              gunicorn wajo_backend.wsgi:application --workers 3 --bind 0.0.0.0:8000 --access-logfile /var/log/gunicorn.access.log --error-logfile /var/log/gunicorn.error.log
            "
    ports:
      - "8002:8000"
    volumes:
      - .:/app
      - pilot_media_volume:/app/media
    restart: 'always'

  pilot_wajo_media_server:
    image: nginx:latest
    container_name: pilot_wajo_media_server
    ports:
      - "8082:80"
    volumes:
      - ./nginx/media_server.conf:/etc/nginx/conf.d/media.conf
      - pilot_media_volume:/usr/share/nginx/html/media
    environment:
      - VIRTUAL_HOST=api.hiwajo.com
    restart: 'always'
    depends_on:
      - pilot_wajo_backend


volumes:
  pilot_media_volume:
