services:
  wajo-redis:
    image: redis:7-alpine
    container_name: wajo-redis
    ports:
      - "6379:6379"

  django:
    build:
      context: .
      dockerfile: Dockerfile
    image: wajo-app:latest
    container_name: wajo-app
    entrypoint: ""
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - django-settings-module=wajo_backend.settings
    depends_on:
      - wajo-redis

  wajo-celery-worker:
    image: wajo-app:latest
    container_name: wajo-celery-worker
    entrypoint: ""
    command: celery -A wajo_backend worker --loglevel=INFO
    volumes:
      - .:/app
      - media_volume:/app/media
    env_file:
      - .env
    environment:
      - django-settings-module=wajo_backend.settings
      - celery-broker-url=redis://wajo-redis:6379/0
    depends_on:
      - wajo-redis
  # wajo-celery-beat:
  #   image: wajo-app:latest
  #   container_name: wajo-celery-beat
  #   entrypoint: ""
  #   command: celery -A wajo_backend beat --loglevel=INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
  #   volumes:
  #     - .:/app
  #     - media_volume:/app/media
  #   env_file:
  #     - .env
  #   environment:
  #     - django-settings-module=wajo_backend.settings
  #     - celery-broker-url=redis://wajo-redis:6379/0
  #   depends_on:
  #     - wajo-redis

volumes:
  media_volume:
