# Required project information
sonar.projectKey=Wajo-Backend
sonar.projectName=Wajo-Backend
sonar.projectVersion=1.0

# Directory containing source code
sonar.sources=.

# Exclude migrations and test directories
sonar.exclusions=**/migrations/**,**/__pycache__/**,**/static/**,**/media/**

# Python interpreter version
sonar.python.version=3.x
