# Generated by Django 5.0.10 on 2026-01-06 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEventEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('sub_category', models.CharField(max_length=30)),
                ('detail', models.TextField(max_length=1000)),
                ('title', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(max_length=250)),
                ('repeat', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly'), ('Custom', 'Custom'), ('None', 'None')], max_length=15)),
                ('custom_repeat', models.JSONField(blank=True, default=dict)),
                ('participants', models.CharField(max_length=250)),
                ('notes', models.TextField(blank=True, max_length=1000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='accounts.wajouser')),
            ],
            options={
                'verbose_name_plural': 'Calendar Event Entries',
            },
        ),
        migrations.CreateModel(
            name='CalendarGoalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=250)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('notes', models.TextField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_goals', to='accounts.wajouser')),
            ],
            options={
                'verbose_name_plural': 'Calendar Goal Entries',
            },
        ),
    ]
