# Generated by Django 5.0.10 on 2025-02-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_entry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevententry',
            name='category',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='calendarevententry',
            name='sub_category',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='calendargoalentry',
            name='category',
            field=models.CharField(max_length=30),
        ),
    ]
