# Generated by Django 5.0.10 on 2025-02-28 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_entry', '0002_alter_calendarevententry_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendarevententry',
            options={'verbose_name_plural': 'Calendar Event Entries'},
        ),
        migrations.AlterModelOptions(
            name='calendargoalentry',
            options={'verbose_name_plural': 'Calendar Goal Entries'},
        ),
    ]
