# Generated by Django 5.0.4 on 2024-11-24 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyWellnessQuestionnaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("q_id", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=50)),
                ("language", models.CharField(max_length=10)),
                ("description", models.TextField()),
                ("question_to_ask", models.TextField()),
                ("response_choices", models.JSONField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Daily Wellness Questionnaire",
                "verbose_name_plural": "Daily Wellness Questionnaire",
            },
        ),
        migrations.CreateModel(
            name="RPEQuestionnaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("q_id", models.CharField(max_length=20)),
                ("after_session_type", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=50)),
                ("language", models.CharField(max_length=10)),
                ("description", models.TextField()),
                ("question_to_ask", models.TextField()),
                ("response_choices", models.JSONField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "RPE Questionnaire",
                "verbose_name_plural": "RPE Questionnaire",
            },
        ),
        migrations.CreateModel(
            name="SchedulePlanningQuestionnaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_id", models.CharField(max_length=20)),
                ("step", models.IntegerField()),
                ("language", models.CharField(max_length=10)),
                ("user_role", models.CharField(blank=True, max_length=150, null=True)),
                ("age", models.CharField(blank=True, max_length=150, null=True)),
                ("category", models.CharField(blank=True, max_length=150, null=True)),
                ("question", models.TextField(blank=True, null=True)),
                (
                    "response_type",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("options_or_instructions", models.TextField(blank=True, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Schedule Planning Questionnaire",
                "verbose_name_plural": "Schedule Planning Questionnaire",
            },
        ),
        migrations.CreateModel(
            name="DailyWellnessUserResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("response", models.JSONField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_wellness_user_response",
                        to="accounts.wajouser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Wellness User Response",
                "verbose_name_plural": "Daily Wellness User Responses",
            },
        ),
        migrations.CreateModel(
            name="RPEUserResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("response", models.JSONField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rpe_user_response",
                        to="accounts.wajouser",
                    ),
                ),
            ],
            options={
                "verbose_name": "RPE User Response",
                "verbose_name_plural": "RPE User Responses",
            },
        ),
        migrations.CreateModel(
            name="SchedulePlanningResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("response", models.JSONField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shchedule_planning_response",
                        to="accounts.wajouser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Schedule Planning User Response",
                "verbose_name_plural": "Schedule Planning User Responses",
            },
        ),
    ]
