# Generated by Django 5.0.10 on 2024-12-12 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailywellnessquestionnaire",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailywellnessuserresponse",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rpequestionnaire",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rpeuserresponse",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scheduleplanningquestionnaire",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scheduleplanningresponse",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
