# Generated by Django 5.0.4 on 2024-06-25 05:49

import api.models.user
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardSuggestedAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=100)),
                ('action_title', models.CharField(max_length=255)),
                ('action_note', models.TextField(blank=True, null=True)),
                ('postback_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Card Suggested Action',
                'verbose_name_plural': 'Card Suggested Actions',
            },
        ),
        migrations.CreateModel(
            name='DailyWellnessQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('question_to_ask', models.TextField()),
                ('response_choices', models.JSONField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Wellness Questionnaire',
                'verbose_name_plural': 'Daily Wellness Questionnaire',
            },
        ),
        migrations.CreateModel(
            name='WajoUser',
            fields=[
                ('phone_no', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('selected_language', models.CharField(max_length=15)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('nickname', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=15, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('primary_sport', models.CharField(blank=True, max_length=50, null=True)),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('wake_up_time', models.TimeField(blank=True, null=True)),
                ('sleep_time', models.TimeField(blank=True, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=api.models.user.profile_picture_path)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(blank=True, limit_choices_to={'role': 'Coach'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='api.wajouser')),
            ],
            options={
                'verbose_name': 'Wajo User',
                'verbose_name_plural': 'Wajo Users',
            },
        ),
        migrations.CreateModel(
            name='OTPStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=15)),
                ('data', models.CharField(max_length=6)),
                ('is_used', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'OTP Store',
                'verbose_name_plural': 'OTP Store',
            },
        ),
        migrations.CreateModel(
            name='RPEQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_id', models.CharField(max_length=20)),
                ('after_session_type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('question_to_ask', models.TextField()),
                ('response_choices', models.JSONField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'RPE Questionnaire',
                'verbose_name_plural': 'RPE Questionnaire',
            },
        ),
        migrations.CreateModel(
            name='SchedulePlanningQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=20)),
                ('step', models.IntegerField()),
                ('language', models.CharField(max_length=10)),
                ('user_role', models.CharField(blank=True, max_length=150, null=True)),
                ('age', models.CharField(blank=True, max_length=150, null=True)),
                ('category', models.CharField(blank=True, max_length=150, null=True)),
                ('question', models.TextField(blank=True, null=True)),
                ('response_type', models.CharField(blank=True, max_length=150, null=True)),
                ('options_or_instructions', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Schedule Planning Questionnaire',
                'verbose_name_plural': 'Schedule Planning Questionnaire',
            },
        ),
        migrations.CreateModel(
            name='OnboardingStep',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='onboarding_step', serialize=False, to='api.wajouser')),
                ('step', models.CharField(default='PQ1', max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Onboarding Flow',
                'verbose_name_plural': 'Onboarding Flow',
            },
        ),
        migrations.CreateModel(
            name='DailyWellnessUserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.JSONField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_wellness_user_response', to='api.wajouser')),
            ],
            options={
                'verbose_name': 'Daily Wellness User Response',
                'verbose_name_plural': 'Daily Wellness User Responses',
            },
        ),
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=255)),
                ('status_code', models.IntegerField()),
                ('request_body', models.TextField(blank=True, null=True)),
                ('response_message', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.wajouser')),
            ],
            options={
                'verbose_name': 'API Log',
                'verbose_name_plural': 'API Logs',
            },
        ),
        migrations.CreateModel(
            name='OneTimeEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(blank=True, max_length=50, null=True)),
                ('event', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=150, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_time_events', to='api.wajouser')),
            ],
            options={
                'verbose_name': 'One Time Event',
                'verbose_name_plural': 'One Time Events',
            },
        ),
        migrations.CreateModel(
            name='RecurringEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(blank=True, max_length=50, null=True)),
                ('event', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=150, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_events', to='api.wajouser')),
            ],
            options={
                'verbose_name': 'Recurring Event',
                'verbose_name_plural': 'Recurring Events',
            },
        ),
        migrations.CreateModel(
            name='RPEUserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.JSONField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rpe_user_response', to='api.wajouser')),
            ],
            options={
                'verbose_name': 'RPE User Response',
                'verbose_name_plural': 'RPE User Responses',
            },
        ),
        migrations.CreateModel(
            name='SchedulePlanningResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.JSONField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shchedule_planning_response', to='api.wajouser')),
            ],
            options={
                'verbose_name': 'Schedule Planning User Response',
                'verbose_name_plural': 'Schedule Planning User Responses',
            },
        ),
        migrations.CreateModel(
            name='StatusCardMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.CharField(blank=True, max_length=10, null=True)),
                ('srpe_score', models.CharField(blank=True, max_length=10, null=True)),
                ('readiness_score', models.CharField(blank=True, max_length=10, null=True)),
                ('sleep_quality', models.CharField(blank=True, max_length=10, null=True)),
                ('fatigue_score', models.CharField(blank=True, max_length=10, null=True)),
                ('mood_score', models.CharField(blank=True, max_length=10, null=True)),
                ('play_time', models.CharField(blank=True, max_length=10, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_card_metrics', to='api.wajouser')),
            ],
            options={
                'verbose_name': 'Status Card Metrics',
                'verbose_name_plural': 'Status Card Metrics',
            },
        ),
        migrations.CreateModel(
            name='WajoUserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcm_token', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='api.wajouser')),
            ],
            options={
                'verbose_name': 'Wajo User Device',
                'verbose_name_plural': 'Wajo User Devices',
                'unique_together': {('user', 'fcm_token')},
            },
        ),
    ]
