# Generated by Django 5.0.4 on 2024-04-17 05:55

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wajouser",
            name="activities",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wajouser",
            name="affiliation",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="wajouser",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wajouser",
            name="gender",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="wajouser",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="wajouser",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="wajouser",
            name="nickname",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="wajouser",
            name="picture",
            field=models.ImageField(
                blank=True, null=True, upload_to=api.models.profile_picture_path
            ),
        ),
        migrations.AddField(
            model_name="wajouser",
            name="primary_sport",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="wajouser",
            name="role",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="wajouser",
            name="sleep_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wajouser",
            name="wake_up_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
