# Generated by Django 5.0.4 on 2024-07-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimeevents',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recurringevents',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
