# Generated by Django 5.0.4 on 2024-07-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_onetimeevents_date_alter_recurringevents_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringevents',
            name='frequency',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], default='Daily', max_length=15),
        ),
    ]
