# Generated by Django 5.0.4 on 2024-04-23 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_apilog"),
    ]

    operations = [
        migrations.AddField(
            model_name="apilog",
            name="response_message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
