# Generated by Django 5.0.4 on 2024-07-18 12:28

import api.models.events
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_recurringevents_frequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchEventsDataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('file', models.FileField(upload_to=api.models.events.match_events_data_file_path)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Match Events Data File',
                'verbose_name_plural': 'Match Events Data File',
            },
        ),
    ]
