# Generated by Django 5.0.4 on 2024-04-23 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_apilog_response_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="apilog",
            name="request_body",
            field=models.TextField(blank=True, null=True),
        ),
    ]
