# Generated by Django 5.0.4 on 2024-07-20 06:51

import api.models.events
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_matcheventsdatafile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matcheventsdatafile',
            options={'verbose_name': 'Match Events Data File', 'verbose_name_plural': 'Match Events Data Files'},
        ),
        migrations.AlterField(
            model_name='matcheventsdatafile',
            name='file',
            field=models.FileField(upload_to=api.models.events.match_events_data_file_path, validators=[api.models.events.validate_file_extension]),
        ),
        migrations.CreateModel(
            name='PlayerIDMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_ids', to='api.wajouser')),
            ],
            options={
                'verbose_name': 'Player ID Mapping',
                'verbose_name_plural': 'Player ID Mappings',
            },
        ),
    ]
