# Generated by Django 5.0.4 on 2024-04-24 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_apilog_request_body"),
    ]

    operations = [
        migrations.CreateModel(
            name="OnboardingStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step", models.CharField(default="S1", max_length=10)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_step",
                        to="api.wajouser",
                    ),
                ),
            ],
        ),
    ]
