# Generated by Django 5.0.4 on 2024-07-20 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_performancemetrics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playeridmapping',
            options={'verbose_name': 'Player ID Mappings', 'verbose_name_plural': 'Player ID Mappings'},
        ),
    ]
