# Generated by Django 5.0.4 on 2024-04-24 04:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_onboardingstep"),
    ]

    operations = [
        migrations.RenameField(
            model_name="apilog",
            old_name="created_at",
            new_name="created_on",
        ),
        migrations.AddField(
            model_name="onboardingstep",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="onboardingstep",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
