# Generated by Django 5.0.4 on 2024-04-24 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_rename_created_at_apilog_created_on_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="onboardingstep",
            options={
                "verbose_name": "Onboarding Flow",
                "verbose_name_plural": "Onboarding Flow",
            },
        ),
    ]
