# Generated by Django 5.0.4 on 2024-04-24 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_onboardingstep_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="onboardingstep",
            name="id",
        ),
        migrations.AlterField(
            model_name="onboardingstep",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="onboarding_step",
                serialize=False,
                to="api.wajouser",
            ),
        ),
    ]
