# Generated by Django 5.0.4 on 2024-07-20 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_playeridmapping_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffensivePerformanceMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metrics', models.JSONField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offensive_performance_metrics', to='api.wajouser')),
            ],
            options={
                'verbose_name': 'Offensive Performance Metrics',
                'verbose_name_plural': 'Offensive Performance Metrics',
            },
        ),
    ]
