# Generated by Django 5.0.4 on 2024-04-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_remove_onboardingstep_id_alter_onboardingstep_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onboardingstep",
            name="step",
            field=models.CharField(default="P1", max_length=10),
        ),
    ]
