# Generated by Django 5.0.4 on 2024-04-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_onboardingstep_step"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onboardingstep",
            name="step",
            field=models.CharField(default="PQ1", max_length=10),
        ),
    ]
