# Generated by Django 5.0.4 on 2024-08-16 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_defensiveperformancemetrics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statuscardmetrics',
            name='fatigue_score',
        ),
        migrations.RemoveField(
            model_name='statuscardmetrics',
            name='mood_score',
        ),
        migrations.RemoveField(
            model_name='statuscardmetrics',
            name='overall_score',
        ),
        migrations.RemoveField(
            model_name='statuscardmetrics',
            name='play_time',
        ),
        migrations.RemoveField(
            model_name='statuscardmetrics',
            name='readiness_score',
        ),
        migrations.RemoveField(
            model_name='statuscardmetrics',
            name='sleep_quality',
        ),
        migrations.RemoveField(
            model_name='statuscardmetrics',
            name='srpe_score',
        ),
        migrations.AddField(
            model_name='statuscardmetrics',
            name='metrics',
            field=models.JSONField(default={}),
        ),
    ]
