# Generated by Django 5.0.4 on 2024-08-16 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_statuscardmetrics_fatigue_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuscardmetrics',
            name='metrics',
            field=models.JSONField(default=dict),
        ),
    ]
