# Generated by Django 5.0.4 on 2024-05-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_wajouserdevice"),
    ]

    operations = [
        migrations.AddField(
            model_name="wajouserdevice",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
