# Generated by Django 5.0.4 on 2024-05-04 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_wajouserdevice_updated_on"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="wajouserdevice",
            unique_together={("user", "fcm_token")},
        ),
    ]
