# Generated by Django 5.0.4 on 2024-08-23 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_gamestats'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonOverviewMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metrics', models.JSONField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_overview_metrics', to='api.wajouser')),
            ],
            options={
                'verbose_name': 'Season Overview Metrics',
                'verbose_name_plural': 'Season Overview Metrics',
            },
        ),
    ]
