# Generated by Django 5.0.4 on 2024-05-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_alter_wajouserdevice_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wajouserdevice",
            name="fcm_token",
            field=models.CharField(max_length=255),
        ),
    ]
