# Generated by Django 5.0.4 on 2024-08-23 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_seasonoverviewmetrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='WajoPerformanceIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metrics', models.JSONField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wajo_performance_index', to='api.wajouser')),
            ],
            options={
                'verbose_name': 'Wajo Performance Index',
                'verbose_name_plural': 'Wajo Performance Index',
            },
        ),
    ]
