# Generated by Django 5.0.4 on 2024-08-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_wajoperformanceindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='matcheventsdatafile',
            name='_type',
            field=models.CharField(choices=[('BEPRO', 'BEPRO'), ('GPS', 'GPS')], default='BEPRO', max_length=10),
        ),
    ]
