# Generated by Django 5.0.4 on 2024-05-04 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_alter_wajouserdevice_fcm_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wajouser",
            name="fcm_token",
        ),
    ]
