# Generated by Django 5.0.4 on 2024-08-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_matcheventsdatafile__type'),
    ]

    operations = [
        migrations.AddField(
            model_name='playeridmapping',
            name='player_position',
            field=models.CharField(choices=[('GK', 'Goalkeeper'), ('CB', 'Center Back'), ('LB', 'Left Back'), ('RB', 'Right Back'), ('LWB', 'Left Wing Back'), ('RWB', 'Right Wing Back'), ('CDM', 'Central Defensive Midfielder'), ('CM', 'Central Midfielder'), ('CAM', 'Central Attacking Midfielder'), ('LM', 'Left Midfielder'), ('RM', 'Right Midfielder'), ('LW', 'Left Winger'), ('RW', 'Right Winger'), ('ST', 'Striker'), ('CF', 'Center Forward')], default='ST', max_length=10),
        ),
    ]
