# Generated by Django 5.0.4 on 2024-05-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_remove_wajouser_fcm_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="wajouser",
            name="problems",
            field=models.TextField(blank=True, null=True),
        ),
    ]
