# Generated by Django 5.0.4 on 2024-08-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_playeridmapping_player_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playeridmapping',
            name='player_id',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AddConstraint(
            model_name='playeridmapping',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_user_player_id_mapping'),
        ),
    ]
