# Generated by Django 5.0.4 on 2024-05-07 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_dailywellnessquestionnaire_dailywellnessuserresponse"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="otpstore",
            name="user",
        ),
        migrations.AddField(
            model_name="otpstore",
            name="phone_no",
            field=models.CharField(default="123", max_length=15),
            preserve_default=False,
        ),
    ]
