# Generated by Django 5.0.4 on 2024-09-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wajouser',
            name='coach',
        ),
        migrations.AddField(
            model_name='wajouser',
            name='coach',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'Coach'}, related_name='players', to='api.wajouser'),
        ),
    ]
