# Generated by Django 5.0.4 on 2024-05-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_remove_otpstore_user_otpstore_phone_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailywellnessquestionnaire",
            name="language",
            field=models.CharField(default="en", max_length=10),
            preserve_default=False,
        ),
    ]
