# Generated by Django 5.0.4 on 2024-09-22 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_wajouser_coach_wajouser_coach'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttackingSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metrics', models.JSONField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attacking_skills', to='api.wajouser')),
            ],
            options={
                'verbose_name': 'Attacking Skills',
                'verbose_name_plural': 'Attacking Skills',
            },
        ),
        migrations.CreateModel(
            name='VideoCardDefensive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metrics', models.JSONField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videocard_defensive', to='api.wajouser')),
            ],
            options={
                'verbose_name': 'Video Card Defensive',
                'verbose_name_plural': 'Video Card Defensive',
            },
        ),
        migrations.CreateModel(
            name='VideoCardDistributions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metrics', models.JSONField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videocard_distributions', to='api.wajouser')),
            ],
            options={
                'verbose_name': 'Video Card Distributions',
                'verbose_name_plural': 'Video Card Distributions',
            },
        ),
    ]
