# Generated by Django 5.0.4 on 2024-05-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_dailywellnessquestionnaire_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailywellnessuserresponse",
            name="language",
            field=models.CharField(default="en", max_length=10),
            preserve_default=False,
        ),
    ]
