# Generated by Django 5.0.4 on 2024-05-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_dailywellnessuserresponse_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailywellnessquestionnaire",
            name="q_id",
            field=models.CharField(default="WQ-1", max_length=10),
            preserve_default=False,
        ),
        # migrations.AlterField(
        #     model_name="dailywellnessquestionnaire",
        #     name="id",
        #     field=models.CharField(
        #         auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
        #     ),
        # ),
        migrations.AlterUniqueTogether(
            name="dailywellnessquestionnaire",
            unique_together={("q_id", "language")},
        ),
    ]
