# Generated by Django 5.0.4 on 2024-10-04 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_attackingskills_videocarddefensive_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPSAthleticSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metrics', models.JSONField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athletic_skills', to='api.wajouser')),
            ],
            options={
                'verbose_name': 'GPS-Athletic Skills',
                'verbose_name_plural': 'GPS-Athletic Skills',
            },
        ),
        migrations.CreateModel(
            name='GPSFootballAbilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metrics', models.JSONField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_football_abilities', to='api.wajouser')),
            ],
            options={
                'verbose_name': 'GPS-Football Abilities',
                'verbose_name_plural': 'GPS-Football Abilities',
            },
        ),
    ]
