# Generated by Django 5.0.4 on 2024-10-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_gpsathleticskills_gpsfootballabilities'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachTeamMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(max_length=10, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('coach', models.ManyToManyField(limit_choices_to={'role': 'Coach'}, related_name='coach_team_mappings', to='api.wajouser')),
            ],
            options={
                'verbose_name': 'Coach Team Mappings',
                'verbose_name_plural': 'Coach Team Mappings',
            },
        ),
    ]
