# Generated by Django 5.0.4 on 2024-11-08 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_gpsathleticskills_gpsfootballabilities'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamStats',
            fields=[
                ('team_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('metrics', models.JSONField(default=dict)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Team Stats',
                'verbose_name_plural': 'Team Stats',
            },
        ),
        migrations.CreateModel(
            name='CoachTeamMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('coach', models.OneToOneField(limit_choices_to={'role': 'Coach'}, on_delete=django.db.models.deletion.CASCADE, related_name='coach_team_mappings', to='api.wajouser')),
                ('team_stats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_mappings', to='api.teamstats')),
            ],
            options={
                'verbose_name': 'Coach Team Mapping',
                'verbose_name_plural': 'Coach Team Mappings',
            },
        ),
    ]
