# Generated by Django 5.0.4 on 2024-05-09 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_dailywellnessquestionnaire_q_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dailywellnessuserresponse",
            name="question",
        ),
        migrations.RemoveField(
            model_name="dailywellnessuserresponse",
            name="user",
        ),
        migrations.DeleteModel(
            name="DailyWellnessQuestionnaire",
        ),
        migrations.DeleteModel(
            name="DailyWellnessUserResponse",
        ),
    ]
