# Generated by Django 5.0.4 on 2024-10-24 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_coachteammapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metrics', models.JSONField(default=dict)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('team_mapping', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_stats', to='api.coachteammapping')),
            ],
            options={
                'verbose_name': 'Team Stats',
                'verbose_name_plural': 'Team Stats',
            },
        ),
    ]
