# Generated by Django 5.0.4 on 2024-05-10 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_dailywellnessquestionnaire_dailywellnessuserresponse"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dailywellnessuserresponse",
            name="question",
        ),
        migrations.RemoveField(
            model_name="dailywellnessuserresponse",
            name="user",
        ),
        migrations.DeleteModel(
            name="DailyWellnessQuestionnaire",
        ),
        migrations.DeleteModel(
            name="DailyWellnessUserResponse",
        ),
    ]
