# Generated by Django 5.0.4 on 2024-05-10 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_remove_dailywellnessuserresponse_question_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyWellnessQuestionnaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("q_id", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=50)),
                ("language", models.CharField(max_length=10)),
                ("description", models.TextField()),
                ("question_to_ask", models.TextField()),
                ("response_choices", models.JSONField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
            ],
            options={
                "unique_together": {("q_id", "language")},
            },
        ),
        migrations.CreateModel(
            name="DailyWellnessUserResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("response", models.TextField()),
                ("language", models.CharField(max_length=10)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.dailywellnessquestionnaire",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_wellness_user_response",
                        to="api.wajouser",
                    ),
                ),
            ],
        ),
    ]
