# Generated by Django 5.0.4 on 2024-05-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_rpequestionnaire_rpeuserresponse"),
    ]

    operations = [
        migrations.CreateModel(
            name="CardSuggestedAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_name", models.CharField(max_length=100)),
                ("action_title", models.CharField(max_length=255)),
                ("action_note", models.TextField(blank=True, null=True)),
                (
                    "postback_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
