# Generated by Django 5.0.3 on 2024-05-27 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_cardsuggestedaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailywellnessuserresponse',
            name='set_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rpeuserresponse',
            name='set_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
