# Generated by Django 5.0.3 on 2024-05-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_dailywellnessuserresponse_set_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailywellnessuserresponse',
            name='set_id',
        ),
        migrations.AlterField(
            model_name='dailywellnessuserresponse',
            name='response',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='rpeuserresponse',
            name='response',
            field=models.JSONField(),
        ),
    ]
