# Generated by Django 5.0.3 on 2024-05-27 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_remove_dailywellnessuserresponse_set_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailywellnessuserresponse',
            name='language',
        ),
        migrations.RemoveField(
            model_name='dailywellnessuserresponse',
            name='question',
        ),
        migrations.RemoveField(
            model_name='rpeuserresponse',
            name='language',
        ),
        migrations.RemoveField(
            model_name='rpeuserresponse',
            name='question',
        ),
        migrations.RemoveField(
            model_name='rpeuserresponse',
            name='set_id',
        ),
    ]
