# Generated by Django 5.0.3 on 2024-05-29 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_remove_dailywellnessuserresponse_language_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusCardMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_time', models.CharField(blank=True, max_length=10, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_card_metrics', to='api.wajouser')),
            ],
        ),
    ]
