# Generated by Django 5.0.3 on 2024-05-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_statuscardmetrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuscardmetrics',
            name='play_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
