# Generated by Django 5.0.3 on 2024-05-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_statuscardmetrics_play_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuscardmetrics',
            name='fatigue_score',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='statuscardmetrics',
            name='mood_score',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='statuscardmetrics',
            name='overall_score',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='statuscardmetrics',
            name='readiness_score',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='statuscardmetrics',
            name='sleep_quality',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='statuscardmetrics',
            name='srpe_score',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='statuscardmetrics',
            name='play_time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
