# Generated by Django 5.0.3 on 2024-06-10 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_statuscardmetrics_fatigue_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wajouser',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='wajouser',
            name='affiliation',
        ),
        migrations.RemoveField(
            model_name='wajouser',
            name='location',
        ),
        migrations.RemoveField(
            model_name='wajouser',
            name='problems',
        ),
    ]
