# Generated by Django 5.0.4 on 2024-06-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_remove_wajouser_activities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wajouser',
            name='coaches',
            field=models.ManyToManyField(blank=True, related_name='players', to='api.wajouser'),
        ),
    ]
