# Generated by Django 5.0.4 on 2024-06-19 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_wajouser_coaches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wajouser',
            name='coaches',
        ),
        migrations.AddField(
            model_name='wajouser',
            name='coaches',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'coach'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='api.wajouser'),
        ),
    ]
