# Generated by Django 5.0.4 on 2024-06-19 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_remove_wajouser_coaches_wajouser_coaches'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wajouser',
            old_name='coaches',
            new_name='coach',
        ),
    ]
