# Generated by Django 5.0.4 on 2024-06-19 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_rename_coaches_wajouser_coach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wajouser',
            name='coach',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Coach'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='api.wajouser'),
        ),
    ]
