# Generated by Django 5.0.4 on 2024-06-24 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_wajouser_coach'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitiesQuestionnaire',
            fields=[
                ('activity_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=10)),
                ('user_role', models.CharField(blank=True, max_length=150, null=True)),
                ('category', models.CharField(blank=True, max_length=150, null=True)),
                ('activity_type', models.CharField(blank=True, max_length=150, null=True)),
                ('event_description', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('typical_time', models.CharField(blank=True, max_length=150, null=True)),
                ('warnings_or_considerations', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=150, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
