# Generated by Django 5.0.4 on 2024-06-24 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_activitiesquestionnaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitiesquestionnaire',
            name='duration',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
