# Generated by Django 5.0.4 on 2024-06-24 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_activitiesquestionnaire_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitiesquestionnaire',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activitiesquestionnaire',
            name='activity_id',
            field=models.BigIntegerField(),
        ),
    ]
