# Generated by Django 5.0.4 on 2024-06-25 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_activitiesquestionnaire_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulePlanningQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=20)),
                ('step', models.IntegerField()),
                ('language', models.CharField(max_length=10)),
                ('user_role', models.CharField(blank=True, max_length=150, null=True)),
                ('age', models.CharField(blank=True, max_length=150, null=True)),
                ('category', models.CharField(blank=True, max_length=150, null=True)),
                ('question', models.TextField(blank=True, null=True)),
                ('response_type', models.CharField(blank=True, max_length=150, null=True)),
                ('options_or_instructions', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchedulePlanningResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.JSONField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shchedule_planning_response', to='api.wajouser')),
            ],
        ),
    ]
