# Generated by Django 5.0.4 on 2024-06-25 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_onetimeevents_recurringevents'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivitiesQuestionnaire',
        ),
        migrations.AlterModelOptions(
            name='apilog',
            options={'verbose_name': 'API Log', 'verbose_name_plural': 'API Logs'},
        ),
        migrations.AlterModelOptions(
            name='cardsuggestedaction',
            options={'verbose_name': 'Card Suggested Action', 'verbose_name_plural': 'Card Suggested Actions'},
        ),
        migrations.AlterModelOptions(
            name='dailywellnessquestionnaire',
            options={'verbose_name': 'Daily Wellness Questionnaire', 'verbose_name_plural': 'Daily Wellness Questionnaire'},
        ),
        migrations.AlterModelOptions(
            name='dailywellnessuserresponse',
            options={'verbose_name': 'Daily Wellness User Response', 'verbose_name_plural': 'Daily Wellness User Responses'},
        ),
        migrations.AlterModelOptions(
            name='onetimeevents',
            options={'verbose_name': 'One Time Event', 'verbose_name_plural': 'One Time Events'},
        ),
        migrations.AlterModelOptions(
            name='otpstore',
            options={'verbose_name': 'OTP Store', 'verbose_name_plural': 'OTP Store'},
        ),
        migrations.AlterModelOptions(
            name='recurringevents',
            options={'verbose_name': 'Recurring Event', 'verbose_name_plural': 'Recurring Events'},
        ),
        migrations.AlterModelOptions(
            name='rpequestionnaire',
            options={'verbose_name': 'RPE Questionnaire', 'verbose_name_plural': 'RPE Questionnaire'},
        ),
        migrations.AlterModelOptions(
            name='rpeuserresponse',
            options={'verbose_name': 'RPE User Response', 'verbose_name_plural': 'RPE User Responses'},
        ),
        migrations.AlterModelOptions(
            name='scheduleplanningquestionnaire',
            options={'verbose_name': 'Schedule Planning Questionnaire', 'verbose_name_plural': 'Schedule Planning Questionnaire'},
        ),
        migrations.AlterModelOptions(
            name='scheduleplanningresponse',
            options={'verbose_name': 'Schedule Planning User Response', 'verbose_name_plural': 'Schedule Planning User Responses'},
        ),
        migrations.AlterModelOptions(
            name='statuscardmetrics',
            options={'verbose_name': 'Status Card Metrics', 'verbose_name_plural': 'Status Card Metrics'},
        ),
        migrations.AlterModelOptions(
            name='wajouser',
            options={'verbose_name': 'Wajo User', 'verbose_name_plural': 'Wajo Users'},
        ),
        migrations.AlterModelOptions(
            name='wajouserdevice',
            options={'verbose_name': 'Wajo User Device', 'verbose_name_plural': 'Wajo User Devices'},
        ),
        migrations.AlterUniqueTogether(
            name='dailywellnessquestionnaire',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='rpequestionnaire',
            unique_together=set(),
        ),
    ]
