# Generated by Django 5.0.10 on 2026-01-06 12:37

import accounts.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTPStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=15)),
                ('data', models.CharField(max_length=6)),
                ('is_used', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'OTP Store',
                'verbose_name_plural': 'OTP Store',
            },
        ),
        migrations.CreateModel(
            name='PlayerIDMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('player_id', models.CharField(max_length=10, unique=True)),
                ('player_position', models.CharField(choices=[('GK', 'Goalkeeper'), ('CB', 'Center Back'), ('LB', 'Left Back'), ('RB', 'Right Back'), ('LWB', 'Left Wing Back'), ('RWB', 'Right Wing Back'), ('CDM', 'Central Defensive Midfielder'), ('CM', 'Central Midfielder'), ('CAM', 'Central Attacking Midfielder'), ('LM', 'Left Midfielder'), ('RM', 'Right Midfielder'), ('LW', 'Left Winger'), ('RW', 'Right Winger'), ('ST', 'Striker'), ('CF', 'Center Forward')], default='ST', max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Player ID Mappings',
                'verbose_name_plural': 'Player ID Mappings',
            },
        ),
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('account_deletion', 'Account Deletion')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'User Request',
                'verbose_name_plural': 'User Requests',
            },
        ),
        migrations.CreateModel(
            name='WajoUserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcm_token', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Wajo User Device',
                'verbose_name_plural': 'Wajo User Devices',
            },
        ),
        migrations.CreateModel(
            name='WajoUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_no', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('country_code', models.CharField(blank=True, max_length=10, null=True)),
                ('is_registered', models.BooleanField(default=False)),
                ('created_via', models.CharField(choices=[('MANUAL', 'Manual Registration'), ('EXCEL', 'Excel Data Import')], default='MANUAL', max_length=50)),
                ('selected_language', models.CharField(max_length=15)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('nickname', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=15, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('primary_sport', models.CharField(blank=True, max_length=50, null=True)),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('wake_up_time', models.TimeField(blank=True, null=True)),
                ('sleep_time', models.TimeField(blank=True, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=accounts.models.profile_picture_path)),
                ('jersey_number', models.IntegerField(blank=True, null=True)),
                ('language_metadata', models.JSONField(blank=True, default=dict, help_text="Multilingual match data with 'en' and 'he' sections containing match summary, lineups, replacements, bench, coaches, and referees", null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('coach', models.ManyToManyField(blank=True, limit_choices_to={'role': 'Coach'}, related_name='players', to='accounts.wajouser')),
            ],
            options={
                'verbose_name': 'Wajo User',
                'verbose_name_plural': 'Wajo Users',
            },
        ),
    ]
