# Generated by Django 5.0.4 on 2024-11-23 08:08

import accounts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OTPStore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_no", models.CharField(max_length=15)),
                ("data", models.CharField(max_length=6)),
                ("is_used", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "OTP Store",
                "verbose_name_plural": "OTP Store",
            },
        ),
        migrations.CreateModel(
            name="WajoUser",
            fields=[
                (
                    "phone_no",
                    models.CharField(
                        max_length=15, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("selected_language", models.CharField(max_length=15)),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("nickname", models.CharField(blank=True, max_length=50, null=True)),
                ("gender", models.CharField(blank=True, max_length=15, null=True)),
                ("dob", models.DateField(blank=True, null=True)),
                (
                    "primary_sport",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("role", models.CharField(blank=True, max_length=50, null=True)),
                ("wake_up_time", models.TimeField(blank=True, null=True)),
                ("sleep_time", models.TimeField(blank=True, null=True)),
                (
                    "picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=accounts.models.profile_picture_path,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "coach",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"role": "Coach"},
                        related_name="players",
                        to="accounts.wajouser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wajo User",
                "verbose_name_plural": "Wajo Users",
            },
        ),
        migrations.CreateModel(
            name="PlayerIDMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_id", models.CharField(max_length=10, unique=True)),
                (
                    "player_position",
                    models.CharField(
                        choices=[
                            ("GK", "Goalkeeper"),
                            ("CB", "Center Back"),
                            ("LB", "Left Back"),
                            ("RB", "Right Back"),
                            ("LWB", "Left Wing Back"),
                            ("RWB", "Right Wing Back"),
                            ("CDM", "Central Defensive Midfielder"),
                            ("CM", "Central Midfielder"),
                            ("CAM", "Central Attacking Midfielder"),
                            ("LM", "Left Midfielder"),
                            ("RM", "Right Midfielder"),
                            ("LW", "Left Winger"),
                            ("RW", "Right Winger"),
                            ("ST", "Striker"),
                            ("CF", "Center Forward"),
                        ],
                        default="ST",
                        max_length=10,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_ids",
                        to="accounts.wajouser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Player ID Mappings",
                "verbose_name_plural": "Player ID Mappings",
            },
        ),
        migrations.CreateModel(
            name="WajoUserDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fcm_token", models.CharField(max_length=255)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="accounts.wajouser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wajo User Device",
                "verbose_name_plural": "Wajo User Devices",
            },
        ),
        migrations.AddConstraint(
            model_name="playeridmapping",
            constraint=models.UniqueConstraint(
                fields=("user",), name="accounts_unique_user_player_id_mapping"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="wajouserdevice",
            unique_together={("user", "fcm_token")},
        ),
    ]
