# Generated by Django 5.0.10 on 2026-01-06 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wajouser',
            name='team',
            field=models.ForeignKey(blank=True, help_text='Team this user belongs to (for players)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='teams.team'),
        ),
        migrations.AddField(
            model_name='userrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='accounts.wajouser'),
        ),
        migrations.AddField(
            model_name='playeridmapping',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_ids', to='accounts.wajouser'),
        ),
        migrations.AddField(
            model_name='wajouserdevice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='accounts.wajouser'),
        ),
        migrations.AddConstraint(
            model_name='playeridmapping',
            constraint=models.UniqueConstraint(fields=('user',), name='accounts_unique_user_player_id_mapping'),
        ),
        migrations.AlterUniqueTogether(
            name='wajouserdevice',
            unique_together={('user', 'fcm_token')},
        ),
    ]
