# Generated by Django 5.0.10 on 2024-12-12 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_otpstore_deleted_at_playeridmapping_deleted_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wajouser",
            name="deleted_at",
        ),
    ]
