# Generated by Django 5.0.10 on 2024-12-12 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_wajouser_deleted_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="otpstore",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="wajouserdevice",
            name="deleted_at",
        ),
    ]
