# Generated by Django 5.0.10 on 2025-08-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='wajouser',
            name='jersey_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
