# Generated by Django 5.0.10 on 2025-09-03 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_wajouser_jersey_number'),
        ('teams', '0005_alter_team_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='wajouser',
            name='team',
            field=models.ForeignKey(blank=True, help_text='Team this user belongs to (for players)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='teams.team'),
        ),
    ]
