# Generated by Django 5.0.10 on 2025-12-30 12:40

import uuid
from django.db import migrations, models

def gen_uuid(apps, schema_editor):
    WajoUser = apps.get_model('accounts', 'WajoUser')
    db_alias = schema_editor.connection.alias
    for row in WajoUser.objects.using(db_alias).all():
        if not row.id:
            row.id = uuid.uuid4()
            row.save(update_fields=['id'])

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_wajouser_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='wajouser',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wajouser',
            name='country_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='wajouser',
            name='created_via',
            field=models.CharField(choices=[('MANUAL', 'Manual Registration'), ('EXCEL', 'Excel Data Import')], default='MANUAL', max_length=50),
        ),
        migrations.AddField(
            model_name='wajouser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='wajouser',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
        
        # We do the PK swap here
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # 1. Add the column as nullable first
                migrations.RunSQL("ALTER TABLE accounts_wajouser ADD COLUMN id uuid;"),
                # 2. Populate it (we use RunPython below, but we need the column to exist in DB)
            ],
            state_operations=[
                # Tell Django 'id' exists now as a field
                migrations.AddField(
                    model_name='wajouser',
                    name='id',
                    field=models.UUIDField(editable=False, null=True),
                ),
            ]
        ),
        
        # 3. Populate existing rows with UUIDs
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
        
        # 4. Now perform the hard swap in DB and State
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Drop old PK, make id NOT NULL, make id the new PK
                migrations.RunSQL([
                    "ALTER TABLE accounts_wajouser DROP CONSTRAINT IF EXISTS accounts_wajouser_pkey CASCADE;",
                    "ALTER TABLE accounts_wajouser ALTER COLUMN id SET NOT NULL;",
                    "ALTER TABLE accounts_wajouser ADD PRIMARY KEY (id);",
                ])
            ],
            state_operations=[
                # Change phone_no to non-PK
                migrations.AlterField(
                    model_name='wajouser',
                    name='phone_no',
                    field=models.CharField(blank=True, max_length=15, null=True, unique=True),
                ),
                # Change id to PK
                migrations.AlterField(
                    model_name='wajouser',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
            ]
        ),
    ]
