# Generated by Django 5.0.10 on 2025-12-30 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_wajouser_country_wajouser_country_code_and_more'),
    ]

    operations = [
    ]
