# Generated by Django 5.0.10 on 2026-01-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_fix_internal_fks'),
    ]

    operations = [
        migrations.AddField(
            model_name='wajouser',
            name='language_metadata',
            field=models.JSONField(blank=True, default=dict, help_text="Multilingual match data with 'en' and 'he' sections containing match summary, lineups, replacements, bench, coaches, and referees", null=True),
        ),
    ]
