# Generated by Django 4.2.20 on 2025-04-15 17:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('match_data', '0003_matchsummarystats_alter_beproformationdata_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostMatchAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview_json', models.JSONField()),
                ('overview_json_he', models.JSONField()),
                ('key_tactical_insight_report_json', models.JSONField()),
                ('key_tactical_insight_report_json_he', models.JSONField()),
                ('individual_player_performance_report_json', models.JSONField()),
                ('individual_player_performance_report_json_he', models.JSONField()),
                ('team_performance_report_json', models.JSONField()),
                ('team_performance_report_json_he', models.JSONField()),
                ('set_piece_analysis_report_json', models.JSONField()),
                ('set_piece_analysis_report_json_he', models.JSONField()),
                ('fitness_recovery_suggestion_json', models.JSONField()),
                ('fitness_recovery_suggestion_json_he', models.JSONField()),
                ('training_recommendation_report_json', models.JSONField()),
                ('training_recommendation_report_json_he', models.JSONField()),
                ('summary_json', models.JSONField()),
                ('summary_json_he', models.JSONField()),
            ],
            options={
                'verbose_name_plural': 'Post Match Analysis',
            },
        ),
        migrations.DeleteModel(
            name='MatchSummaryStats',
        ),
        migrations.AlterField(
            model_name='beproformationdata',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6a5ca34e-db7e-420f-ac45-9cc10ecf8d3d'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='beproleaguedetail',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ecb02126-b6f4-44a2-b336-295002d6b1d3'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='beprolineup',
            name='id',
            field=models.UUIDField(default=uuid.UUID('37d29ace-7e83-4af3-869b-549f0f258d77'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bepromatchdata',
            name='id',
            field=models.UUIDField(default=uuid.UUID('130298b4-7fea-4114-9582-b3eec7e1b227'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bepromatchdetail',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0f73a02c-2eda-41b4-b3de-0f6b9bc26cef'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='beprophysicaleventdata',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c7d65b61-99b5-43bb-85af-f2ae5553bd94'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='beproplayer',
            name='id',
            field=models.UUIDField(default=uuid.UUID('23bfdd00-2aea-4710-9ba0-18e376715745'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='beproplayerstat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('071fe914-e0ad-4c4e-baf9-b41ae271d7c3'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='beproplayerstatsextended',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0326af18-b0d2-481b-861b-ff0f0e25bd51'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='beproseason',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e45ad69a-8201-42b2-84bc-1693237bcd69'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='beprosequencedata',
            name='id',
            field=models.UUIDField(default=uuid.UUID('68de8915-9c9c-4b0a-8e64-463510612e57'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='beproteamstat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1f1a2781-eb3f-4652-98ac-bdd129bc3459'), primary_key=True, serialize=False),
        ),
    ]
