# Generated by Django 5.0.10 on 2025-06-26 06:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_data', '0004_postmatchanalysis_delete_matchsummarystats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beproformationdata',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5e2ea3cb-3ef5-436b-bb76-302eb4259cc1'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='beproleaguedetail',
            name='id',
            field=models.UUIDField(default=uuid.UUID('71409978-da92-4950-acae-97e950786333'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='beprolineup',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2514d1c5-204a-45a7-98cd-978a21f9fd9f'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bepromatchdata',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a5f7dc89-aa34-43d2-8323-3cb029aadc90'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bepromatchdetail',
            name='id',
            field=models.UUIDField(default=uuid.UUID('adc4f37c-ad2a-4b1f-aaa8-9434fff74dcf'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='beprophysicaleventdata',
            name='id',
            field=models.UUIDField(default=uuid.UUID('60ba0f2d-6eb2-43ce-8fa9-3d6f471dc2d1'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='beproplayer',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7c077014-8e83-47ed-b88e-61a7b3d5e47a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='beproplayerstat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b414b56c-0746-4c7a-81aa-9390e1756d79'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='beproplayerstatsextended',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1283c753-70ca-46da-80bc-76d1421c2c12'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='beproseason',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d320b89a-154f-4338-a889-78b10b6ee2ee'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='beprosequencedata',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b0407cff-4508-4512-95cd-f20c0d54cbdb'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='beproteamstat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c0bb080c-28b4-4aaf-a698-f382e73a2728'), primary_key=True, serialize=False),
        ),
    ]
