# Generated by Django 5.0.10 on 2025-08-01 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_userrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=250)),
                ('match_date', models.DateField()),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('home_score', models.PositiveSmallIntegerField()),
                ('away_score', models.PositiveSmallIntegerField()),
                ('video_url', models.URLField()),
                ('result', models.JSONField(default=dict)),
                ('status', models.CharField(default='waiting_for_data', help_text='Status of the session processing', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.wajouser')),
            ],
        ),
        migrations.CreateModel(
            name='TracePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('jersey_number', models.PositiveIntegerField()),
                ('team', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracevision.tracesession')),
            ],
        ),
    ]
