# Generated by Django 5.0.10 on 2025-07-29 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_userrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchDataTracevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('video', models.FileField(upload_to='match_data_videos/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.wajouser')),
            ],
        ),
    ]
