# Generated by Django 5.0.10 on 2025-10-02 04:46

import django.db.models.deletion
import tracevision.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_wajouser_team'),
        ('teams', '0004_team_jersey_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='TracePlayer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('object_id', models.CharField(help_text='Unique identifier from TraceVision API', max_length=100, null=True)),
                ('name', models.CharField(help_text="Player's name", max_length=100)),
                ('jersey_number', models.PositiveIntegerField(help_text="Player's jersey number")),
                ('position', models.CharField(help_text="Player's position on the field", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('team', models.ForeignKey(help_text='Team this player belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='trace_players', to='teams.team')),
                ('user', models.ForeignKey(blank=True, help_text='User who owns this player data (optional for unmapped players)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trace_players', to='accounts.wajouser')),
            ],
            options={
                'verbose_name': 'Trace Player',
                'verbose_name_plural': 'Trace Players',
            },
        ),
        migrations.CreateModel(
            name='TraceHighlight',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('highlight_id', models.CharField(help_text='Unique identifier for the highlight', max_length=100, unique=True)),
                ('video_id', models.PositiveIntegerField(help_text='Video ID associated with the highlight')),
                ('start_offset', models.PositiveIntegerField(help_text='Start offset in milliseconds')),
                ('duration', models.PositiveIntegerField(help_text='Duration of the highlight in milliseconds')),
                ('tags', models.JSONField(default=list, help_text='Tags associated with the highlight')),
                ('video_stream', models.URLField(help_text='URL to the video stream')),
                ('event_type', models.CharField(choices=[('touch', 'Touch'), ('touch-chain', 'Touch Chain'), ('goal', 'Goal'), ('yellow_card', 'Yellow Card'), ('red_card', 'Red Card'), ('substitution', 'Substitution'), ('save', 'Save'), ('shot', 'Shot'), ('pass', 'Pass'), ('tackle', 'Tackle'), ('foul', 'Foul'), ('offside', 'Offside'), ('corner', 'Corner'), ('free_kick', 'Free Kick'), ('penalty', 'Penalty'), ('other', 'Other')], default='touch', help_text='Type of event this highlight represents', max_length=20)),
                ('source', models.CharField(choices=[('tracevision', 'TraceVision API'), ('excel_import', 'Excel Import'), ('manual', 'Manual Entry'), ('ai_detection', 'AI Detection')], default='tracevision', help_text='Source of this highlight data', max_length=20)),
                ('match_time', models.CharField(blank=True, help_text="Match time when event occurred in MM:SS format (e.g., '16:30', '77:15')", max_length=8, null=True)),
                ('half', models.PositiveIntegerField(blank=True, help_text='Match half (1 or 2) when event occurred', null=True)),
                ('event_metadata', models.JSONField(default=dict, help_text='Additional event-specific data (scorer, card type, etc.)')),
                ('performance_impact', models.FloatField(default=0.0, help_text='Impact score on player performance (0-100)')),
                ('team_impact', models.FloatField(default=0.0, help_text='Impact score on team performance (0-100)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(blank=True, help_text='Player involved in this highlight (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='tracevision.traceplayer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TraceSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=250)),
                ('match_date', models.DateField()),
                ('home_score', models.PositiveSmallIntegerField()),
                ('away_score', models.PositiveSmallIntegerField()),
                ('age_group', models.CharField(blank=True, choices=[('U11_U12', 'U11-U12 (9v9)'), ('U13_U14', 'U13-U14 (11v11)'), ('U15_U16', 'U15-U16 (11v11)'), ('U17_U18', 'U17-U18 (11v11)'), ('SENIOR', 'Senior (18+)')], default='SENIOR', help_text='Age group of the players in this session', max_length=10, null=True)),
                ('pitch_size', models.JSONField(blank=True, default=tracevision.models.get_default_pitch_size, help_text="Football field dimensions in meters: {'length': 105, 'width': 68}", null=True)),
                ('final_score', models.CharField(help_text="Final score in format 'home_score-away_score' (e.g., '2-1')", max_length=10)),
                ('start_time', models.DateTimeField(blank=True, help_text='Start time of the video, if known', null=True)),
                ('video_url', models.URLField()),
                ('blob_video_url', models.URLField(blank=True, help_text='Azure blob URL for downloaded video file', null=True)),
                ('result', models.JSONField(default=dict)),
                ('result_blob_url', models.URLField(blank=True, help_text='Azure blob URL for session result data JSON', null=True)),
                ('status', models.CharField(default='waiting_for_data', help_text='Status of the session processing', max_length=20)),
                ('match_start_time', models.CharField(blank=True, help_text="Match start time in format 'HH:MM:SS'", max_length=20, null=True)),
                ('first_half_end_time', models.CharField(blank=True, help_text="First half end time in format 'HH:MM:SS'", max_length=20, null=True)),
                ('second_half_start_time', models.CharField(blank=True, help_text="Second half start time in format 'HH:MM:SS'", max_length=20, null=True)),
                ('match_end_time', models.CharField(blank=True, help_text="Match end time in format 'HH:MM:SS'", max_length=20, null=True)),
                ('basic_game_stats', models.FileField(blank=True, help_text='Basic game stats file', null=True, upload_to='basic_game_stats/')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the session was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the session was last updated')),
                ('away_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='away_team', to='teams.team')),
                ('home_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='home_team', to='teams.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.wajouser')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TracePossessionSegment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('side', models.CharField(max_length=10)),
                ('start_ms', models.IntegerField()),
                ('end_ms', models.IntegerField()),
                ('count', models.IntegerField(default=0)),
                ('start_clock', models.CharField(blank=True, max_length=20)),
                ('end_clock', models.CharField(blank=True, max_length=20)),
                ('duration_s', models.FloatField(default=0.0)),
                ('team_metrics', models.JSONField(default=dict, help_text='Cumulative team possession metrics up to this highlight')),
                ('player_metrics', models.JSONField(default=dict, help_text='Player involvement metrics for this highlight')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('highlight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='possession_segments', to='tracevision.tracehighlight')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='possession_segments', to='tracevision.tracesession')),
            ],
            options={
                'verbose_name': 'Possession Segment',
                'verbose_name_plural': 'Possession Segments',
            },
        ),
        migrations.AddField(
            model_name='traceplayer',
            name='session',
            field=models.ForeignKey(help_text='TraceVision session this player belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='trace_players', to='tracevision.tracesession'),
        ),
        migrations.CreateModel(
            name='TracePassingNetwork',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('side', models.CharField(max_length=10)),
                ('passes_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_player', models.ForeignKey(blank=True, help_text='Player who made the passes', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passing_network_from', to='tracevision.traceplayer')),
                ('to_player', models.ForeignKey(blank=True, help_text='Player who received the passes', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passing_network_to', to='tracevision.traceplayer')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passing_network', to='tracevision.tracesession')),
            ],
            options={
                'verbose_name': 'Passing Network Edge',
                'verbose_name_plural': 'Passing Network Edges',
            },
        ),
        migrations.CreateModel(
            name='TracePass',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('side', models.CharField(max_length=10)),
                ('start_ms', models.IntegerField()),
                ('duration_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_player', models.ForeignKey(blank=True, help_text='Player who made the pass', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passes_made', to='tracevision.traceplayer')),
                ('to_player', models.ForeignKey(blank=True, help_text='Player who received the pass', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passes_received', to='tracevision.traceplayer')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes', to='tracevision.tracesession')),
            ],
            options={
                'verbose_name': 'Pass',
                'verbose_name_plural': 'Passes',
            },
        ),
        migrations.CreateModel(
            name='TraceObject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('object_id', models.CharField(help_text='Unique identifier for the object', max_length=120)),
                ('type', models.CharField(help_text='Type of the object', max_length=100)),
                ('side', models.CharField(help_text='Side/team the object belongs to', max_length=100)),
                ('appearance_fv', models.JSONField(blank=True, help_text='Appearance feature vector', null=True)),
                ('color_fv', models.JSONField(blank=True, help_text='Color feature vector', null=True)),
                ('tracking_url', models.URLField(help_text='URL to fetch tracking data', max_length=500)),
                ('tracking_blob_url', models.URLField(blank=True, help_text='Azure blob URL for downloaded tracking data', max_length=500, null=True)),
                ('role', models.CharField(blank=True, help_text='Role of the object', max_length=50, null=True)),
                ('tracking_processed', models.BooleanField(default=False, help_text='Whether tracking data has been processed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(blank=True, help_text='Player this object belongs to (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trace_objects', to='tracevision.traceplayer')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trace_objects', to='tracevision.tracesession')),
            ],
            options={
                'ordering': ['object_id'],
            },
        ),
        migrations.AddField(
            model_name='tracehighlight',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='tracevision.tracesession'),
        ),
        migrations.CreateModel(
            name='TraceCoachReportTeam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('side', models.CharField(max_length=10)),
                ('goals', models.IntegerField(default=0)),
                ('shots', models.IntegerField(default=0)),
                ('passes', models.IntegerField(default=0)),
                ('possession_time_s', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_report_team', to='tracevision.tracesession')),
            ],
            options={
                'verbose_name': 'Coach Report Team',
                'verbose_name_plural': 'Coach Report Team',
            },
        ),
        migrations.CreateModel(
            name='TraceClipReel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_id', models.CharField(help_text='Unique event identifier', max_length=100)),
                ('video_type', models.CharField(choices=[('original', 'Original (No Overlay)'), ('with_overlay', 'With Overlay'), ('zoomed_player', 'Zoomed on Player'), ('zoomed_team', 'Zoomed on Team'), ('tactical_view', 'Tactical View'), ('slow_motion', 'Slow Motion'), ('multi_angle', 'Multi-Angle')], default='original', help_text='Type of video variation', max_length=20)),
                ('video_variant_name', models.CharField(blank=True, help_text="Custom name for this video variant (e.g., 'Player Focus', 'Team View')", max_length=100)),
                ('event_type', models.CharField(help_text='Type of event (touch, pass, etc.)', max_length=50)),
                ('side', models.CharField(help_text='Team side (home/away)', max_length=10)),
                ('start_ms', models.IntegerField(help_text='Start time in milliseconds')),
                ('duration_ms', models.IntegerField(help_text='Duration in milliseconds')),
                ('start_clock', models.CharField(blank=True, help_text='Start time in clock format', max_length=20)),
                ('end_clock', models.CharField(blank=True, help_text='End time in clock format', max_length=20)),
                ('generation_status', models.CharField(choices=[('pending', 'Pending Generation'), ('generating', 'Currently Generating'), ('completed', 'Generation Completed'), ('failed', 'Generation Failed'), ('skipped', 'Skipped')], default='pending', help_text='Status of video generation', max_length=20)),
                ('video_url', models.URLField(blank=True, help_text='Azure blob URL for the generated video')),
                ('video_thumbnail_url', models.URLField(blank=True, help_text='Azure blob URL for video thumbnail')),
                ('video_size_mb', models.FloatField(default=0.0, help_text='Video file size in MB')),
                ('video_duration_seconds', models.FloatField(default=0.0, help_text='Actual video duration in seconds')),
                ('generation_started_at', models.DateTimeField(blank=True, help_text='When video generation started', null=True)),
                ('generation_completed_at', models.DateTimeField(blank=True, help_text='When video generation completed', null=True)),
                ('generation_errors', models.JSONField(default=list, help_text='Any errors during generation')),
                ('generation_metadata', models.JSONField(default=dict, help_text='Additional generation parameters and settings')),
                ('resolution', models.CharField(default='1080p', help_text='Video resolution', max_length=20)),
                ('frame_rate', models.IntegerField(default=30, help_text='Video frame rate (FPS)')),
                ('bitrate', models.IntegerField(default=0, help_text='Video bitrate (kbps)')),
                ('label', models.CharField(blank=True, help_text='Display label for the clip', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the clip')),
                ('tags', models.JSONField(default=list, help_text='Tags for categorization and filtering')),
                ('video_stream', models.URLField(blank=True, help_text='Legacy video stream URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('highlight', models.ForeignKey(help_text='The highlight this clip reel is based on', on_delete=django.db.models.deletion.CASCADE, related_name='clip_reels', to='tracevision.tracehighlight')),
                ('involved_players', models.ManyToManyField(blank=True, help_text='All players involved in this highlight', related_name='involved_clip_reels', to='tracevision.traceplayer')),
                ('primary_player', models.ForeignKey(blank=True, help_text='Primary player involved in this clip', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_clip_reels', to='tracevision.traceplayer')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clip_reels', to='tracevision.tracesession')),
            ],
            options={
                'verbose_name': 'Clip Reel Item',
                'verbose_name_plural': 'Clip Reel Items',
            },
        ),
        migrations.CreateModel(
            name='TraceTouchLeaderboard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('object_side', models.CharField(max_length=10)),
                ('touches', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(blank=True, help_text='Player this touch count belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='touch_leaderboard', to='tracevision.traceplayer')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='touch_leaderboard', to='tracevision.tracesession')),
            ],
            options={
                'verbose_name': 'Touch Leaderboard Entry',
                'verbose_name_plural': 'Touch Leaderboard Entries',
            },
        ),
        migrations.CreateModel(
            name='TraceVisionPlayerStats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('side', models.CharField(help_text='home or away team', max_length=10)),
                ('total_distance_meters', models.FloatField(default=0.0, help_text='Total distance covered in meters')),
                ('avg_speed_mps', models.FloatField(default=0.0, help_text='Average speed in meters per second')),
                ('max_speed_mps', models.FloatField(default=0.0, help_text='Maximum speed reached')),
                ('total_time_seconds', models.FloatField(default=0.0, help_text='Total time tracked in seconds')),
                ('sprint_count', models.PositiveIntegerField(default=0, help_text='Number of sprints detected')),
                ('sprint_distance_meters', models.FloatField(default=0.0, help_text='Total distance covered in sprints')),
                ('sprint_time_seconds', models.FloatField(default=0.0, help_text='Total time spent sprinting')),
                ('avg_position_x', models.FloatField(default=0.0, help_text='Average X position (0-1000 scale)')),
                ('avg_position_y', models.FloatField(default=0.0, help_text='Average Y position (0-1000 scale)')),
                ('position_variance', models.FloatField(default=0.0, help_text='Position variance (movement range)')),
                ('heatmap_data', models.JSONField(default=dict, help_text='Heatmap grid data for visualization')),
                ('performance_score', models.FloatField(default=0.0, help_text='Overall performance score 0-100')),
                ('stamina_rating', models.FloatField(default=0.0, help_text='Stamina rating based on movement patterns')),
                ('work_rate', models.FloatField(default=0.0, help_text='Work rate based on distance and speed')),
                ('calculation_method', models.CharField(default='standard', help_text='Method used for calculations', max_length=100)),
                ('calculation_version', models.CharField(default='1.0', help_text='Calculation algorithm version', max_length=20)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(blank=True, help_text='Player this statistics belong to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='tracevision.traceplayer')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_player_stats', to='tracevision.tracesession')),
            ],
            options={
                'verbose_name': 'TraceVision Player Stats',
                'verbose_name_plural': 'TraceVision Player Stats',
            },
        ),
        migrations.CreateModel(
            name='TraceVisionSessionStats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('home_team_stats', models.JSONField(default=dict, help_text='Home team aggregated stats')),
                ('away_team_stats', models.JSONField(default=dict, help_text='Away team aggregated stats')),
                ('possession_data', models.JSONField(default=dict, help_text='Possession percentages and patterns')),
                ('tactical_analysis', models.JSONField(default=dict, help_text='Formation and tactical insights')),
                ('total_tracking_points', models.PositiveIntegerField(default=0, help_text='Total tracking data points')),
                ('data_coverage_percentage', models.FloatField(default=0.0, help_text='Percentage of video with tracking data')),
                ('quality_score', models.FloatField(default=0.0, help_text='Overall data quality score')),
                ('processing_status', models.CharField(default='pending', help_text='Stats processing status', max_length=20)),
                ('processing_errors', models.JSONField(default=list, help_text='Any errors during processing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_stats', to='tracevision.tracesession')),
            ],
            options={
                'verbose_name': 'TraceVision Session Stats',
                'verbose_name_plural': 'TraceVision Session Stats',
            },
        ),
        migrations.CreateModel(
            name='TraceHighlightObject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('highlight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlight_objects', to='tracevision.tracehighlight')),
                ('trace_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_highlights', to='tracevision.traceobject')),
                ('player', models.ForeignKey(blank=True, help_text='Player involved in this highlight-object relationship (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highlight_objects', to='tracevision.traceplayer')),
            ],
            options={
                'indexes': [models.Index(fields=['highlight'], name='tracevision_highlig_c77a6c_idx'), models.Index(fields=['trace_object'], name='tracevision_trace_o_931ac9_idx'), models.Index(fields=['player'], name='tracevision_player__93cb0d_idx')],
                'unique_together': {('highlight', 'trace_object')},
            },
        ),
        migrations.CreateModel(
            name='TracePossessionStats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('possession_type', models.CharField(choices=[('team', 'Team'), ('player', 'Player')], max_length=10)),
                ('side', models.CharField(blank=True, choices=[('home', 'Home'), ('away', 'Away')], max_length=10, null=True)),
                ('metrics', models.JSONField(default=dict, help_text='All possession metrics stored in JSON format. Structure varies by type: team metrics include possession_percentage, total_possessions, etc. Player metrics include touches_in_possession, involvement_percentage, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='possession_stats', to='tracevision.traceplayer')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='possession_stats', to='teams.team')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='possession_stats', to='tracevision.tracesession')),
            ],
            options={
                'verbose_name': 'Possession Stats',
                'verbose_name_plural': 'Possession Stats',
                'indexes': [models.Index(fields=['session', 'possession_type'], name='tracevision_session_41f1b3_idx'), models.Index(fields=['session', 'possession_type', 'team'], name='tracevision_session_643adf_idx'), models.Index(fields=['session', 'possession_type', 'player'], name='tracevision_session_303e62_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='tracepossessionstats',
            constraint=models.UniqueConstraint(condition=models.Q(('possession_type', 'team')), fields=('session', 'possession_type', 'team', 'side'), name='unique_team_possession_stats'),
        ),
        migrations.AddConstraint(
            model_name='tracepossessionstats',
            constraint=models.UniqueConstraint(condition=models.Q(('possession_type', 'player')), fields=('session', 'possession_type', 'player'), name='unique_player_possession_stats'),
        ),
        migrations.AddIndex(
            model_name='tracepossessionsegment',
            index=models.Index(fields=['session', 'side'], name='tracevision_session_3880ed_idx'),
        ),
        migrations.AddIndex(
            model_name='tracepossessionsegment',
            index=models.Index(fields=['session', 'start_ms'], name='tracevision_session_8cb16a_idx'),
        ),
        migrations.AddIndex(
            model_name='tracepossessionsegment',
            index=models.Index(fields=['highlight'], name='tracevision_highlig_67f89f_idx'),
        ),
        migrations.AddIndex(
            model_name='traceplayer',
            index=models.Index(fields=['object_id'], name='tracevision_object__9971bd_idx'),
        ),
        migrations.AddIndex(
            model_name='traceplayer',
            index=models.Index(fields=['user'], name='tracevision_user_id_0361ed_idx'),
        ),
        migrations.AddIndex(
            model_name='traceplayer',
            index=models.Index(fields=['team'], name='tracevision_team_id_892a83_idx'),
        ),
        migrations.AddIndex(
            model_name='traceplayer',
            index=models.Index(fields=['session'], name='tracevision_session_17d54f_idx'),
        ),
        migrations.AddConstraint(
            model_name='traceplayer',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('object_id', 'user'), name='unique_object_id_per_user'),
        ),
        migrations.AddConstraint(
            model_name='traceplayer',
            constraint=models.UniqueConstraint(fields=('object_id', 'session'), name='unique_object_id_per_session'),
        ),
        migrations.AddIndex(
            model_name='tracepassingnetwork',
            index=models.Index(fields=['session', 'side'], name='tracevision_session_b347b5_idx'),
        ),
        migrations.AddIndex(
            model_name='tracepassingnetwork',
            index=models.Index(fields=['passes_count'], name='tracevision_passes__52fa01_idx'),
        ),
        migrations.AddIndex(
            model_name='tracepass',
            index=models.Index(fields=['session', 'side'], name='tracevision_session_2b48d2_idx'),
        ),
        migrations.AddIndex(
            model_name='tracepass',
            index=models.Index(fields=['session', 'from_player', 'to_player'], name='tracevision_session_8955bf_idx'),
        ),
        migrations.AddIndex(
            model_name='traceobject',
            index=models.Index(fields=['object_id'], name='tracevision_object__f0ad10_idx'),
        ),
        migrations.AddIndex(
            model_name='traceobject',
            index=models.Index(fields=['session', 'type'], name='tracevision_session_852af5_idx'),
        ),
        migrations.AddIndex(
            model_name='traceobject',
            index=models.Index(fields=['session', 'side'], name='tracevision_session_70e732_idx'),
        ),
        migrations.AddIndex(
            model_name='traceobject',
            index=models.Index(fields=['player', 'type'], name='tracevision_player__d288e5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='traceobject',
            unique_together={('object_id', 'session')},
        ),
        migrations.AddIndex(
            model_name='tracehighlight',
            index=models.Index(fields=['highlight_id'], name='tracevision_highlig_258d97_idx'),
        ),
        migrations.AddIndex(
            model_name='tracehighlight',
            index=models.Index(fields=['session', 'start_offset'], name='tracevision_session_b07bb7_idx'),
        ),
        migrations.AddIndex(
            model_name='tracehighlight',
            index=models.Index(fields=['player', '-created_at'], name='tracevision_player__2680f7_idx'),
        ),
        migrations.AddIndex(
            model_name='tracehighlight',
            index=models.Index(fields=['event_type', 'session'], name='tracevision_event_t_9ae343_idx'),
        ),
        migrations.AddIndex(
            model_name='tracehighlight',
            index=models.Index(fields=['source', 'session'], name='tracevision_source_2cbf05_idx'),
        ),
        migrations.AddIndex(
            model_name='tracehighlight',
            index=models.Index(fields=['match_time', 'session'], name='tracevision_match_t_e0fc66_idx'),
        ),
        migrations.AddIndex(
            model_name='tracehighlight',
            index=models.Index(fields=['performance_impact', 'session'], name='tracevision_perform_3276a5_idx'),
        ),
        migrations.AddIndex(
            model_name='tracecoachreportteam',
            index=models.Index(fields=['session', 'side'], name='tracevision_session_55728c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tracecoachreportteam',
            unique_together={('session', 'side')},
        ),
        migrations.AddIndex(
            model_name='traceclipreel',
            index=models.Index(fields=['session', 'side'], name='tracevision_session_97a074_idx'),
        ),
        migrations.AddIndex(
            model_name='traceclipreel',
            index=models.Index(fields=['session', 'event_id'], name='tracevision_session_56f064_idx'),
        ),
        migrations.AddIndex(
            model_name='traceclipreel',
            index=models.Index(fields=['session', 'primary_player'], name='tracevision_session_8536ee_idx'),
        ),
        migrations.AddIndex(
            model_name='traceclipreel',
            index=models.Index(fields=['highlight', 'video_type'], name='tracevision_highlig_3c3e0d_idx'),
        ),
        migrations.AddIndex(
            model_name='traceclipreel',
            index=models.Index(fields=['generation_status', 'created_at'], name='tracevision_generat_932512_idx'),
        ),
        migrations.AddIndex(
            model_name='traceclipreel',
            index=models.Index(fields=['video_type', 'generation_status'], name='tracevision_video_t_b21c15_idx'),
        ),
        migrations.AddIndex(
            model_name='tracetouchleaderboard',
            index=models.Index(fields=['session'], name='tracevision_session_9df88f_idx'),
        ),
        migrations.AddIndex(
            model_name='tracetouchleaderboard',
            index=models.Index(fields=['object_side', 'touches'], name='tracevision_object__b0120d_idx'),
        ),
        migrations.AddIndex(
            model_name='tracevisionplayerstats',
            index=models.Index(fields=['session', 'player'], name='tracevision_session_0ceddf_idx'),
        ),
        migrations.AddIndex(
            model_name='tracevisionplayerstats',
            index=models.Index(fields=['side', 'performance_score'], name='tracevision_side_4d1e1e_idx'),
        ),
        migrations.AddIndex(
            model_name='tracevisionplayerstats',
            index=models.Index(fields=['performance_score', 'last_calculated'], name='tracevision_perform_803492_idx'),
        ),
        migrations.AddIndex(
            model_name='tracevisionsessionstats',
            index=models.Index(fields=['session'], name='tracevision_session_df7614_idx'),
        ),
        migrations.AddIndex(
            model_name='tracevisionsessionstats',
            index=models.Index(fields=['processing_status', 'created_at'], name='tracevision_process_b83ddb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tracevisionsessionstats',
            unique_together={('session',)},
        ),
    ]
