# Generated by Django 5.0.10 on 2026-01-22 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('tracevision', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traceclipreel',
            name='caption',
            field=models.TextField(blank=True, help_text="Reel owner's caption/description", null=True),
        ),
        migrations.CreateModel(
            name='TraceClipReelComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='Comment text content')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private to Owner')], default='public', help_text='Public: visible to all with reel access. Private: visible only to reel owner', max_length=10)),
                ('mentions', models.JSONField(default=list, help_text='Mentioned users: [{"user_id": "uuid", "username": "name"}]')),
                ('is_edited', models.BooleanField(default=False, help_text='Whether comment was edited')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='When comment was deleted', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(help_text='User who wrote the comment', on_delete=django.db.models.deletion.CASCADE, related_name='clip_comments', to='accounts.wajouser')),
                ('clip_reel', models.ForeignKey(help_text='The reel this comment is on', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tracevision.traceclipreel')),
                ('highlight', models.ForeignKey(help_text='Source highlight for tracking', on_delete=django.db.models.deletion.CASCADE, related_name='clip_comments', to='tracevision.tracehighlight')),
                ('parent_comment', models.ForeignKey(blank=True, help_text='Parent comment for threaded replies', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='tracevision.traceclipreelcomment')),
            ],
            options={
                'verbose_name': 'Clip Reel Comment',
                'verbose_name_plural': 'Clip Reel Comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TraceClipReelCommentEditHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('previous_content', models.TextField(help_text='Content before the edit')),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(help_text='The comment that was edited', on_delete=django.db.models.deletion.CASCADE, related_name='edit_history', to='tracevision.traceclipreelcomment')),
                ('edited_by', models.ForeignKey(help_text='User who made the edit (usually the author)', on_delete=django.db.models.deletion.CASCADE, to='accounts.wajouser')),
            ],
            options={
                'verbose_name': 'Comment Edit History',
                'verbose_name_plural': 'Comment Edit Histories',
                'ordering': ['-edited_at'],
            },
        ),
        migrations.CreateModel(
            name='TraceClipReelCommentLike',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(help_text='The comment being liked', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='tracevision.traceclipreelcomment')),
                ('user', models.ForeignKey(help_text='User who liked the comment', on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to='accounts.wajouser')),
            ],
            options={
                'verbose_name': 'Comment Like',
                'verbose_name_plural': 'Comment Likes',
            },
        ),
        migrations.CreateModel(
            name='TraceClipReelNote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='Note content')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='When note was deleted', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(help_text='User who wrote the note (must be Player or Coach)', on_delete=django.db.models.deletion.CASCADE, related_name='clip_notes', to='accounts.wajouser')),
                ('clip_reel', models.ForeignKey(help_text='The reel this note is about', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='tracevision.traceclipreel')),
                ('highlight', models.ForeignKey(help_text='Source highlight for tracking', on_delete=django.db.models.deletion.CASCADE, related_name='clip_notes', to='tracevision.tracehighlight')),
            ],
            options={
                'verbose_name': 'Clip Reel Note',
                'verbose_name_plural': 'Clip Reel Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TraceClipReelNoteShare',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shared_with_group', models.CharField(blank=True, choices=[('team_coaches', 'All Team Coaches'), ('player_coach', "Player's Coach")], help_text='Group to share with (for group sharing)', max_length=20, null=True)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the share is active (for revoking access)')),
                ('note', models.ForeignKey(help_text='The note being shared', on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='tracevision.traceclipreelnote')),
                ('shared_by', models.ForeignKey(help_text='User who shared the note', on_delete=django.db.models.deletion.CASCADE, related_name='note_shares_made', to='accounts.wajouser')),
                ('shared_with_user', models.ForeignKey(blank=True, help_text='Specific user to share with (for individual sharing)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_shares_received', to='accounts.wajouser')),
            ],
            options={
                'verbose_name': 'Note Share',
                'verbose_name_plural': 'Note Shares',
            },
        ),
        migrations.CreateModel(
            name='TraceClipReelShare',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('can_comment', models.BooleanField(default=True, help_text='Whether recipient can comment on this reel')),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the share is active (for revoking access)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clip_reel', models.ForeignKey(help_text='The reel being shared', on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='tracevision.traceclipreel')),
                ('highlight', models.ForeignKey(help_text='Source highlight for tracking', on_delete=django.db.models.deletion.CASCADE, related_name='reel_shares', to='tracevision.tracehighlight')),
                ('shared_by', models.ForeignKey(help_text='User who shared the reel', on_delete=django.db.models.deletion.CASCADE, related_name='reels_shared', to='accounts.wajouser')),
                ('shared_with', models.ForeignKey(help_text='User who received access to the reel', on_delete=django.db.models.deletion.CASCADE, related_name='reels_received', to='accounts.wajouser')),
            ],
            options={
                'verbose_name': 'Clip Reel Share',
                'verbose_name_plural': 'Clip Reel Shares',
            },
        ),
        migrations.AddIndex(
            model_name='traceclipreelcomment',
            index=models.Index(fields=['clip_reel', 'created_at'], name='tracevision_clip_re_1a92d4_idx'),
        ),
        migrations.AddIndex(
            model_name='traceclipreelcomment',
            index=models.Index(fields=['author'], name='tracevision_author__b166bb_idx'),
        ),
        migrations.AddIndex(
            model_name='traceclipreelcomment',
            index=models.Index(fields=['highlight'], name='tracevision_highlig_5ba8b2_idx'),
        ),
        migrations.AddIndex(
            model_name='traceclipreelcomment',
            index=models.Index(fields=['parent_comment'], name='tracevision_parent__187488_idx'),
        ),
        migrations.AddIndex(
            model_name='traceclipreelcomment',
            index=models.Index(fields=['visibility', 'is_deleted'], name='tracevision_visibil_33465b_idx'),
        ),
        migrations.AddIndex(
            model_name='traceclipreelcommentedithistory',
            index=models.Index(fields=['comment', 'edited_at'], name='tracevision_comment_e05999_idx'),
        ),
        migrations.AddIndex(
            model_name='traceclipreelcommentlike',
            index=models.Index(fields=['comment', 'created_at'], name='tracevision_comment_703d1e_idx'),
        ),
        migrations.AddIndex(
            model_name='traceclipreelcommentlike',
            index=models.Index(fields=['user'], name='tracevision_user_id_0c54cc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='traceclipreelcommentlike',
            unique_together={('comment', 'user')},
        ),
        migrations.AddIndex(
            model_name='traceclipreelnote',
            index=models.Index(fields=['clip_reel', 'author'], name='tracevision_clip_re_2af218_idx'),
        ),
        migrations.AddIndex(
            model_name='traceclipreelnote',
            index=models.Index(fields=['highlight'], name='tracevision_highlig_053ac6_idx'),
        ),
        migrations.AddIndex(
            model_name='traceclipreelnote',
            index=models.Index(fields=['is_deleted'], name='tracevision_is_dele_670996_idx'),
        ),
        migrations.AddIndex(
            model_name='traceclipreelnoteshare',
            index=models.Index(fields=['note', 'shared_with_user'], name='tracevision_note_id_5014d8_idx'),
        ),
        migrations.AddIndex(
            model_name='traceclipreelnoteshare',
            index=models.Index(fields=['note', 'shared_with_group'], name='tracevision_note_id_67211e_idx'),
        ),
        migrations.AddIndex(
            model_name='traceclipreelnoteshare',
            index=models.Index(fields=['shared_by'], name='tracevision_shared__0c0809_idx'),
        ),
        migrations.AddConstraint(
            model_name='traceclipreelnoteshare',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('shared_with_group__isnull', True), ('shared_with_user__isnull', False)), models.Q(('shared_with_group__isnull', False), ('shared_with_user__isnull', True)), _connector='OR'), name='note_share_user_or_group'),
        ),
        migrations.AddIndex(
            model_name='traceclipreelshare',
            index=models.Index(fields=['clip_reel', 'shared_with'], name='tracevision_clip_re_07e4ea_idx'),
        ),
        migrations.AddIndex(
            model_name='traceclipreelshare',
            index=models.Index(fields=['shared_by'], name='tracevision_shared__c43497_idx'),
        ),
        migrations.AddIndex(
            model_name='traceclipreelshare',
            index=models.Index(fields=['is_active'], name='tracevision_is_acti_78fb2d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='traceclipreelshare',
            unique_together={('clip_reel', 'shared_with')},
        ),
    ]
