# Generated by Django 5.0.10 on 2025-11-24 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_wajouser_team"),
        ("games", "0012_gameuserrole"),
        ("teams", "0004_team_jersey_color"),
        ("tracevision", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tracesession",
            name="game",
            field=models.OneToOneField(
                blank=True,
                help_text="Canonical game this session belongs to (OneToOne: one game = one session)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trace_session",
                to="games.game",
            ),
        ),
        migrations.AddIndex(
            model_name="tracesession",
            index=models.Index(
                fields=["video_url"], name="tracevision_video_u_e615b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tracesession",
            index=models.Index(
                fields=["home_team", "away_team", "match_date"],
                name="tracevision_home_te_8909d4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tracesession",
            index=models.Index(fields=["game"], name="tracevision_game_id_9fed99_idx"),
        ),
        migrations.AddConstraint(
            model_name="tracesession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("video_url__isnull", False)),
                fields=("video_url",),
                name="unique_video_url",
            ),
        ),
        migrations.AddConstraint(
            model_name="tracesession",
            constraint=models.UniqueConstraint(
                fields=("home_team", "away_team", "match_date"),
                name="unique_game_match",
            ),
        ),
    ]
