# Generated by Django 5.0.10 on 2025-08-14 07:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracevision', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tracesession',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='tracesession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='When the session was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tracesession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When the session was last updated'),
        ),
    ]
