# Generated by Django 5.0.10 on 2025-07-30 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracevision', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TracePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('jersey_number', models.PositiveIntegerField()),
                ('team', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('session', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='TraceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=250)),
                ('match_date', models.DateField()),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('home_score', models.PositiveSmallIntegerField()),
                ('away_score', models.PositiveSmallIntegerField()),
                ('match_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracevision.matchdatatracevision')),
            ],
        ),
    ]
