# Generated by Django 5.0.10 on 2025-11-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracevision', '0002_tracesession_game_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traceclipreel',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Whether this is the default video variation for the highlight'),
        ),
        migrations.AddField(
            model_name='traceclipreel',
            name='ratio',
            field=models.CharField(choices=[('original', 'Original (Horizontal)'), ('9:16', 'Vertical (9:16)')], default='original', help_text='Video aspect ratio (original/horizontal or 9:16/vertical)', max_length=20),
        ),
        migrations.AlterField(
            model_name='traceclipreel',
            name='tags',
            field=models.JSONField(default=list, help_text='Tags for overlay options: with_player_title, without_player_title, with_circle, without_circle'),
        ),
    ]
