# Generated by Django 5.0.10 on 2026-02-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('tracevision', '0002_traceclipreel_caption_traceclipreelcomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traceclipreelnote',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', help_text='public: visible to all users with clip reel access. private: visible only to the author and explicitly shared users.', max_length=10),
        ),
        migrations.AddIndex(
            model_name='traceclipreelnote',
            index=models.Index(fields=['visibility', 'is_deleted'], name='tracevision_visibil_4de9ec_idx'),
        ),
    ]
