# Generated by Django 5.0.10 on 2025-08-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracevision', '0002_alter_tracesession_options_tracesession_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracesession',
            name='away_team_jersey_color',
            field=models.CharField(default=0, help_text='Hex color code for away team jersey (e.g., #0000FF)', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tracesession',
            name='final_score',
            field=models.CharField(default=0, help_text="Final score in format 'home_score-away_score' (e.g., '2-1')", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tracesession',
            name='home_team_jersey_color',
            field=models.CharField(default=0, help_text='Hex color code for home team jersey (e.g., #FF0000)', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tracesession',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text='Start time of the video, if known', null=True),
        ),
    ]
