# Generated by Django 5.0.10 on 2025-07-30 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracevision', '0002_traceplayer_tracesession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traceplayer',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracevision.tracesession'),
        ),
    ]
