# Generated by Django 5.0.10 on 2025-08-18 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userrequest'),
        ('tracevision', '0003_tracesession_away_team_jersey_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraceHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlight_id', models.CharField(help_text='Unique identifier for the highlight', max_length=100, unique=True)),
                ('video_id', models.PositiveIntegerField(help_text='Video ID associated with the highlight')),
                ('start_offset', models.PositiveIntegerField(help_text='Start offset in milliseconds')),
                ('duration', models.PositiveIntegerField(help_text='Duration of the highlight in milliseconds')),
                ('tags', models.JSONField(default=list, help_text='Tags associated with the highlight')),
                ('video_stream', models.URLField(help_text='URL to the video stream')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='tracevision.tracesession')),
                ('user', models.ForeignKey(help_text='User who owns this highlight', on_delete=django.db.models.deletion.CASCADE, related_name='trace_highlights', to='accounts.wajouser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TraceObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(help_text='Unique identifier for the object', max_length=120)),
                ('type', models.CharField(help_text='Type of the object', max_length=100)),
                ('side', models.CharField(help_text='Side/team the object belongs to', max_length=100)),
                ('appearance_fv', models.JSONField(blank=True, help_text='Appearance feature vector', null=True)),
                ('color_fv', models.JSONField(blank=True, help_text='Color feature vector', null=True)),
                ('tracking_url', models.URLField(help_text='URL to fetch tracking data')),
                ('role', models.CharField(blank=True, help_text='Role of the object', max_length=50, null=True)),
                ('tracking_data', models.JSONField(default=list, help_text='Parsed tracking data points (time_off, x, y, w, h)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trace_objects', to='tracevision.tracesession')),
                ('user', models.ForeignKey(help_text='User who owns this object', on_delete=django.db.models.deletion.CASCADE, related_name='user_trace_objects', to='accounts.wajouser')),
            ],
            options={
                'ordering': ['object_id'],
            },
        ),
        migrations.CreateModel(
            name='TraceHighlightObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('highlight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlight_objects', to='tracevision.tracehighlight')),
                ('trace_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_highlights', to='tracevision.traceobject')),
            ],
        ),
        migrations.CreateModel(
            name='TrackingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_off', models.FloatField(help_text='Time offset in seconds')),
                ('x', models.FloatField(help_text='X coordinate')),
                ('y', models.FloatField(help_text='Y coordinate')),
                ('w', models.FloatField(help_text='Width')),
                ('h', models.FloatField(help_text='Height')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trace_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_points', to='tracevision.traceobject')),
                ('user', models.ForeignKey(help_text='User who owns this tracking data', on_delete=django.db.models.deletion.CASCADE, related_name='tracking_data', to='accounts.wajouser')),
            ],
            options={
                'ordering': ['time_off'],
            },
        ),
        migrations.AddIndex(
            model_name='tracehighlight',
            index=models.Index(fields=['highlight_id'], name='tracevision_highlig_258d97_idx'),
        ),
        migrations.AddIndex(
            model_name='tracehighlight',
            index=models.Index(fields=['session', 'start_offset'], name='tracevision_session_b07bb7_idx'),
        ),
        migrations.AddIndex(
            model_name='tracehighlight',
            index=models.Index(fields=['user', '-created_at'], name='tracevision_user_id_7f5a80_idx'),
        ),
        migrations.AddIndex(
            model_name='traceobject',
            index=models.Index(fields=['object_id'], name='tracevision_object__f0ad10_idx'),
        ),
        migrations.AddIndex(
            model_name='traceobject',
            index=models.Index(fields=['session', 'type'], name='tracevision_session_852af5_idx'),
        ),
        migrations.AddIndex(
            model_name='traceobject',
            index=models.Index(fields=['session', 'side'], name='tracevision_session_70e732_idx'),
        ),
        migrations.AddIndex(
            model_name='traceobject',
            index=models.Index(fields=['user', 'type'], name='tracevision_user_id_185a10_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='traceobject',
            unique_together={('object_id', 'session')},
        ),
        migrations.AddIndex(
            model_name='tracehighlightobject',
            index=models.Index(fields=['highlight'], name='tracevision_highlig_c77a6c_idx'),
        ),
        migrations.AddIndex(
            model_name='tracehighlightobject',
            index=models.Index(fields=['trace_object'], name='tracevision_trace_o_931ac9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tracehighlightobject',
            unique_together={('highlight', 'trace_object')},
        ),
        migrations.AddIndex(
            model_name='trackingdata',
            index=models.Index(fields=['trace_object', 'time_off'], name='tracevision_trace_o_9be3ff_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingdata',
            index=models.Index(fields=['user', 'time_off'], name='tracevision_user_id_c4325f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='trackingdata',
            unique_together={('trace_object', 'time_off')},
        ),
    ]
