# Generated by Django 5.0.10 on 2026-02-20 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('tracevision', '0003_add_note_visibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraceClipReelNoteReply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='Reply text content')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='When reply was deleted', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(help_text='User who wrote the reply', on_delete=django.db.models.deletion.CASCADE, related_name='note_replies', to='accounts.wajouser')),
                ('note', models.ForeignKey(help_text='The parent note this reply belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='tracevision.traceclipreelnote')),
            ],
            options={
                'verbose_name': 'Note Reply',
                'verbose_name_plural': 'Note Replies',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['note', 'created_at'], name='tracevision_note_id_0491d9_idx'), models.Index(fields=['author'], name='tracevision_author__201dc7_idx'), models.Index(fields=['is_deleted'], name='tracevision_is_dele_9f05fc_idx')],
            },
        ),
    ]
