# Generated by Django 5.0.10 on 2025-12-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracevision', '0003_traceclipreel_is_default_traceclipreel_ratio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traceclipreel',
            name='generation_errors',
            field=models.JSONField(blank=True, default=list, help_text='Any errors during generation', null=True),
        ),
        migrations.AlterField(
            model_name='traceclipreel',
            name='generation_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional generation parameters and settings', null=True),
        ),
        migrations.AlterField(
            model_name='traceclipreel',
            name='video_type',
            field=models.CharField(blank=True, choices=[('original', 'Original (No Overlay)'), ('with_overlay', 'With Overlay'), ('zoomed_player', 'Zoomed on Player'), ('zoomed_team', 'Zoomed on Team'), ('tactical_view', 'Tactical View'), ('slow_motion', 'Slow Motion'), ('multi_angle', 'Multi-Angle')], help_text='Type of video variation (deprecated - use tags and ratio instead)', max_length=20, null=True),
        ),
    ]
