# Generated by Django 5.0.10 on 2025-12-08 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_wajouser_team"),
        ("tracevision", "0004_alter_traceclipreel_generation_errors_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerUserMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mapped_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the mapping was created"
                    ),
                ),
                (
                    "mapping_source",
                    models.CharField(
                        choices=[("api", "API"), ("task", "Task/Automatic")],
                        default="api",
                        help_text="Whether mapping was done via API or automatic task",
                        max_length=10,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about the mapping (e.g., if player was already mapped)",
                        null=True,
                    ),
                ),
                (
                    "mapped_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who performed the mapping (null for automatic/task mappings)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mappings_performed",
                        to="accounts.wajouser",
                    ),
                ),
                (
                    "trace_player",
                    models.ForeignKey(
                        help_text="The TracePlayer being mapped",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mapping_history",
                        to="tracevision.traceplayer",
                    ),
                ),
                (
                    "wajo_user",
                    models.ForeignKey(
                        help_text="The WajoUser being mapped to the player",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_mapping_history",
                        to="accounts.wajouser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Player User Mapping",
                "verbose_name_plural": "Player User Mappings",
                "ordering": ["-mapped_at"],
                "indexes": [
                    models.Index(
                        fields=["trace_player"], name="tracevision_trace_p_50faba_idx"
                    ),
                    models.Index(
                        fields=["wajo_user"], name="tracevision_wajo_us_664559_idx"
                    ),
                    models.Index(
                        fields=["mapped_at"], name="tracevision_mapped__442cdb_idx"
                    ),
                    models.Index(
                        fields=["mapping_source"], name="tracevision_mapping_c436da_idx"
                    ),
                ],
            },
        ),
    ]
