# Generated by Django 5.0.10 on 2025-08-22 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracevision', '0004_tracehighlight_traceobject_tracehighlightobject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraceClipReel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=100)),
                ('video_id', models.IntegerField()),
                ('event_type', models.CharField(max_length=50)),
                ('side', models.CharField(max_length=10)),
                ('start_ms', models.IntegerField()),
                ('duration_ms', models.IntegerField()),
                ('start_clock', models.CharField(blank=True, max_length=20)),
                ('end_clock', models.CharField(blank=True, max_length=20)),
                ('object_id', models.CharField(blank=True, max_length=50, null=True)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('tags', models.JSONField(default=list)),
                ('video_stream', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clip_reels', to='tracevision.tracesession')),
            ],
            options={
                'verbose_name': 'Clip Reel Item',
                'verbose_name_plural': 'Clip Reel Items',
                'indexes': [models.Index(fields=['session', 'side'], name='tracevision_session_97a074_idx'), models.Index(fields=['session', 'event_id'], name='tracevision_session_56f064_idx'), models.Index(fields=['session', 'object_id'], name='tracevision_session_8a4248_idx')],
                'unique_together': {('session', 'event_id', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='TraceCoachReportTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(max_length=10)),
                ('goals', models.IntegerField(default=0)),
                ('shots', models.IntegerField(default=0)),
                ('passes', models.IntegerField(default=0)),
                ('possession_time_s', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_report_team', to='tracevision.tracesession')),
            ],
            options={
                'verbose_name': 'Coach Report Team',
                'verbose_name_plural': 'Coach Report Team',
                'indexes': [models.Index(fields=['session', 'side'], name='tracevision_session_55728c_idx')],
                'unique_together': {('session', 'side')},
            },
        ),
        migrations.CreateModel(
            name='TracePass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(max_length=10)),
                ('from_object_id', models.CharField(max_length=50)),
                ('to_object_id', models.CharField(max_length=50)),
                ('start_ms', models.IntegerField()),
                ('duration_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes', to='tracevision.tracesession')),
            ],
            options={
                'verbose_name': 'Pass',
                'verbose_name_plural': 'Passes',
                'indexes': [models.Index(fields=['session', 'side'], name='tracevision_session_2b48d2_idx'), models.Index(fields=['session', 'from_object_id', 'to_object_id'], name='tracevision_session_09274b_idx')],
            },
        ),
        migrations.CreateModel(
            name='TracePassingNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(max_length=10)),
                ('from_object_id', models.CharField(max_length=50)),
                ('to_object_id', models.CharField(max_length=50)),
                ('passes_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passing_network', to='tracevision.tracesession')),
            ],
            options={
                'verbose_name': 'Passing Network Edge',
                'verbose_name_plural': 'Passing Network Edges',
                'indexes': [models.Index(fields=['session', 'side'], name='tracevision_session_b347b5_idx'), models.Index(fields=['passes_count'], name='tracevision_passes__52fa01_idx')],
                'unique_together': {('session', 'side', 'from_object_id', 'to_object_id')},
            },
        ),
        migrations.CreateModel(
            name='TracePossessionSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(max_length=10)),
                ('start_ms', models.IntegerField()),
                ('end_ms', models.IntegerField()),
                ('count', models.IntegerField(default=0)),
                ('start_clock', models.CharField(blank=True, max_length=20)),
                ('end_clock', models.CharField(blank=True, max_length=20)),
                ('duration_s', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='possession_segments', to='tracevision.tracesession')),
            ],
            options={
                'verbose_name': 'Possession Segment',
                'verbose_name_plural': 'Possession Segments',
                'indexes': [models.Index(fields=['session', 'side'], name='tracevision_session_3880ed_idx'), models.Index(fields=['session', 'start_ms'], name='tracevision_session_8cb16a_idx')],
            },
        ),
        migrations.CreateModel(
            name='TraceTouchLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=50)),
                ('object_side', models.CharField(max_length=10)),
                ('touches', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='touch_leaderboard', to='tracevision.tracesession')),
            ],
            options={
                'verbose_name': 'Touch Leaderboard Entry',
                'verbose_name_plural': 'Touch Leaderboard Entries',
                'indexes': [models.Index(fields=['session'], name='tracevision_session_9df88f_idx'), models.Index(fields=['object_side', 'touches'], name='tracevision_object__b0120d_idx')],
                'unique_together': {('session', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='TraceVisionPlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(help_text='TraceVision object ID (e.g., home_1, away_15)', max_length=50)),
                ('side', models.CharField(help_text='home or away team', max_length=10)),
                ('total_distance_meters', models.FloatField(default=0.0, help_text='Total distance covered in meters')),
                ('avg_speed_mps', models.FloatField(default=0.0, help_text='Average speed in meters per second')),
                ('max_speed_mps', models.FloatField(default=0.0, help_text='Maximum speed reached')),
                ('total_time_seconds', models.FloatField(default=0.0, help_text='Total time tracked in seconds')),
                ('sprint_count', models.PositiveIntegerField(default=0, help_text='Number of sprints detected')),
                ('sprint_distance_meters', models.FloatField(default=0.0, help_text='Total distance covered in sprints')),
                ('sprint_time_seconds', models.FloatField(default=0.0, help_text='Total time spent sprinting')),
                ('avg_position_x', models.FloatField(default=0.0, help_text='Average X position (0-1000 scale)')),
                ('avg_position_y', models.FloatField(default=0.0, help_text='Average Y position (0-1000 scale)')),
                ('position_variance', models.FloatField(default=0.0, help_text='Position variance (movement range)')),
                ('heatmap_data', models.JSONField(default=dict, help_text='Heatmap grid data for visualization')),
                ('performance_score', models.FloatField(default=0.0, help_text='Overall performance score 0-100')),
                ('stamina_rating', models.FloatField(default=0.0, help_text='Stamina rating based on movement patterns')),
                ('work_rate', models.FloatField(default=0.0, help_text='Work rate based on distance and speed')),
                ('calculation_method', models.CharField(default='standard', help_text='Method used for calculations', max_length=100)),
                ('calculation_version', models.CharField(default='1.0', help_text='Calculation algorithm version', max_length=20)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='tracevision.tracesession')),
            ],
            options={
                'verbose_name': 'TraceVision Player Stats',
                'verbose_name_plural': 'TraceVision Player Stats',
                'indexes': [models.Index(fields=['session', 'object_id'], name='tracevision_session_8f47c4_idx'), models.Index(fields=['side', 'performance_score'], name='tracevision_side_4d1e1e_idx'), models.Index(fields=['performance_score', 'last_calculated'], name='tracevision_perform_803492_idx')],
                'unique_together': {('session', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='TraceVisionSessionStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team_stats', models.JSONField(default=dict, help_text='Home team aggregated stats')),
                ('away_team_stats', models.JSONField(default=dict, help_text='Away team aggregated stats')),
                ('possession_data', models.JSONField(default=dict, help_text='Possession percentages and patterns')),
                ('tactical_analysis', models.JSONField(default=dict, help_text='Formation and tactical insights')),
                ('total_tracking_points', models.PositiveIntegerField(default=0, help_text='Total tracking data points')),
                ('data_coverage_percentage', models.FloatField(default=0.0, help_text='Percentage of video with tracking data')),
                ('quality_score', models.FloatField(default=0.0, help_text='Overall data quality score')),
                ('processing_status', models.CharField(default='pending', help_text='Stats processing status', max_length=20)),
                ('processing_errors', models.JSONField(default=list, help_text='Any errors during processing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_stats', to='tracevision.tracesession')),
            ],
            options={
                'verbose_name': 'TraceVision Session Stats',
                'verbose_name_plural': 'TraceVision Session Stats',
                'indexes': [models.Index(fields=['session'], name='tracevision_session_df7614_idx'), models.Index(fields=['processing_status', 'created_at'], name='tracevision_process_b83ddb_idx')],
                'unique_together': {('session',)},
            },
        ),
    ]
