# Generated by Django 5.0.10 on 2025-08-27 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_team_jersey_color'),
        ('tracevision', '0005_traceclipreel_tracecoachreportteam_tracepass_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracesession',
            name='away_team_jersey_color',
        ),
        migrations.RemoveField(
            model_name='tracesession',
            name='home_team_jersey_color',
        ),
        migrations.AlterField(
            model_name='tracesession',
            name='away_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='away_team', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='tracesession',
            name='home_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='home_team', to='teams.team'),
        ),
    ]
