# Generated by Django 5.0.10 on 2025-12-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_wajouser_team'),
        ('games', '0013_remove_gameuserrole_role'),
        ('teams', '0004_team_jersey_color'),
        ('tracevision', '0005_playerusermapping'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tracesession',
            name='unique_video_url',
        ),
        migrations.RemoveConstraint(
            model_name='tracesession',
            name='unique_game_match',
        ),
        migrations.AddConstraint(
            model_name='tracesession',
            constraint=models.UniqueConstraint(condition=models.Q(('video_url__isnull', False), models.Q(('status', 'process_error'), _negated=True)), fields=('video_url',), name='unique_video_url'),
        ),
        migrations.AddConstraint(
            model_name='tracesession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'process_error'), _negated=True), fields=('home_team', 'away_team', 'match_date'), name='unique_game_match'),
        ),
    ]
