# Generated by Django 5.0.10 on 2025-12-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracevision', '0007_tracesession_language_metadata_traceplayer_language_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traceplayer',
            old_name='language_data',
            new_name='language_metadata',
        ),
        migrations.AddField(
            model_name='tracehighlight',
            name='video_time',
            field=models.CharField(blank=True, help_text="Actual video time when event occurred in MM:SS format (e.g., '18:16', '23:00')", max_length=8, null=True),
        ),
    ]
