# Generated by Django 5.0.10 on 2025-08-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracevision', '0007_alter_traceclipreel_id_alter_tracecoachreportteam_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracesession',
            name='age_group',
            field=models.CharField(blank=True, choices=[('U11_U12', 'U11-U12 (9v9)'), ('U13_U14', 'U13-U14 (11v11)'), ('U15_U16', 'U15-U16 (11v11)'), ('U17_U18', 'U17-U18 (11v11)'), ('SENIOR', 'Senior (18+)')], default='SENIOR', help_text='Age group of the players in this session', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tracesession',
            name='pitch_size',
            field=models.JSONField(blank=True, default={'length': 105, 'width': 68}, help_text="Football field dimensions in meters: {'length': 105, 'width': 68}", null=True),
        ),
    ]
