# Generated by Django 5.0.10 on 2025-12-29 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_wajouser_team'),
        ('teams', '0006_rename_language_names_team_language_metadata'),
        ('tracevision', '0008_rename_language_data_traceplayer_language_metadata_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='traceplayer',
            name='unique_object_id_per_user',
        ),
        migrations.RemoveConstraint(
            model_name='traceplayer',
            name='unique_object_id_per_session',
        ),
        migrations.RemoveIndex(
            model_name='traceplayer',
            name='tracevision_team_id_892a83_idx',
        ),
        migrations.RemoveIndex(
            model_name='traceplayer',
            name='tracevision_session_17d54f_idx',
        ),
        migrations.RemoveField(
            model_name='traceplayer',
            name='session',
        ),
        migrations.AddField(
            model_name='traceplayer',
            name='account_creation_token',
            field=models.CharField(blank=True, db_index=True, help_text='Unique token for account creation. User can use this token to create account and link to this TracePlayer.', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='traceplayer',
            name='sessions',
            field=models.ManyToManyField(blank=True, help_text='TraceVision sessions this player has participated in', related_name='players', to='tracevision.tracesession'),
        ),
        migrations.AddIndex(
            model_name='traceplayer',
            index=models.Index(fields=['team', 'jersey_number'], name='tracevision_team_id_9676ad_idx'),
        ),
        migrations.AddIndex(
            model_name='traceplayer',
            index=models.Index(fields=['account_creation_token'], name='tracevision_account_8c84c2_idx'),
        ),
        migrations.AddConstraint(
            model_name='traceplayer',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('team', 'jersey_number'), name='unique_team_jersey_no_user'),
        ),
        migrations.AddConstraint(
            model_name='traceplayer',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('team', 'jersey_number', 'user'), name='unique_team_jersey_user'),
        ),
    ]
