# Generated by Django 5.0.10 on 2025-08-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracevision', '0008_tracesession_age_group_tracesession_pitch_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traceobject',
            name='tracking_data',
        ),
        migrations.AddField(
            model_name='traceobject',
            name='tracking_blob_url',
            field=models.URLField(blank=True, help_text='Azure blob URL for downloaded tracking data', null=True),
        ),
        migrations.AddField(
            model_name='traceobject',
            name='tracking_processed',
            field=models.BooleanField(default=False, help_text='Whether tracking data has been processed'),
        ),
        migrations.DeleteModel(
            name='TrackingData',
        ),
    ]
