# Generated by Django 5.0.10 on 2025-12-30 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracevision', '0009_remove_traceplayer_unique_object_id_per_user_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='traceplayer',
            name='tracevision_account_8c84c2_idx',
        ),
        migrations.RemoveField(
            model_name='traceplayer',
            name='account_creation_token',
        ),
    ]
