# Generated by Django 5.0.10 on 2025-09-01 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracevision', '0009_remove_traceobject_tracking_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracesession',
            name='blob_video_url',
            field=models.URLField(blank=True, help_text='Azure blob URL for downloaded video file', null=True),
        ),
        migrations.AddField(
            model_name='tracesession',
            name='result_blob_url',
            field=models.URLField(blank=True, help_text='Azure blob URL for session result data JSON', null=True),
        ),
    ]
