# Generated by Django 5.0.10 on 2025-09-03 04:31

import django.db.models.deletion
import tracevision.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_wajouser_team'),
        ('teams', '0005_alter_team_id'),
        ('tracevision', '0010_tracesession_blob_video_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traceplayer',
            options={'verbose_name': 'Trace Player', 'verbose_name_plural': 'Trace Players'},
        ),
        migrations.RemoveIndex(
            model_name='traceclipreel',
            name='tracevision_session_8a4248_idx',
        ),
        migrations.RemoveIndex(
            model_name='tracehighlight',
            name='tracevision_user_id_7f5a80_idx',
        ),
        migrations.RemoveIndex(
            model_name='traceobject',
            name='tracevision_user_id_185a10_idx',
        ),
        migrations.RemoveIndex(
            model_name='tracepass',
            name='tracevision_session_09274b_idx',
        ),
        migrations.RemoveIndex(
            model_name='tracevisionplayerstats',
            name='tracevision_session_8f47c4_idx',
        ),
        migrations.AlterUniqueTogether(
            name='tracepassingnetwork',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='tracetouchleaderboard',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='tracevisionplayerstats',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='traceclipreel',
            unique_together={('session', 'event_id')},
        ),
        migrations.RemoveField(
            model_name='tracehighlight',
            name='user',
        ),
        migrations.RemoveField(
            model_name='traceobject',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tracepass',
            name='from_object_id',
        ),
        migrations.RemoveField(
            model_name='tracepass',
            name='to_object_id',
        ),
        migrations.AddField(
            model_name='traceclipreel',
            name='player',
            field=models.ForeignKey(blank=True, help_text='Player involved in this clip (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clip_reels', to='tracevision.traceplayer'),
        ),
        migrations.AddField(
            model_name='tracehighlight',
            name='player',
            field=models.ForeignKey(blank=True, help_text='Player involved in this highlight (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='tracevision.traceplayer'),
        ),
        migrations.AddField(
            model_name='tracehighlightobject',
            name='player',
            field=models.ForeignKey(blank=True, help_text='Player involved in this highlight-object relationship (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highlight_objects', to='tracevision.traceplayer'),
        ),
        migrations.AddField(
            model_name='traceobject',
            name='player',
            field=models.ForeignKey(blank=True, help_text='Player this object belongs to (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trace_objects', to='tracevision.traceplayer'),
        ),
        migrations.AddField(
            model_name='tracepass',
            name='from_player',
            field=models.ForeignKey(blank=True, help_text='Player who made the pass', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passes_made', to='tracevision.traceplayer'),
        ),
        migrations.AddField(
            model_name='tracepass',
            name='to_player',
            field=models.ForeignKey(blank=True, help_text='Player who received the pass', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passes_received', to='tracevision.traceplayer'),
        ),
        migrations.AddField(
            model_name='tracepassingnetwork',
            name='from_player',
            field=models.ForeignKey(blank=True, help_text='Player who made the passes', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passing_network_from', to='tracevision.traceplayer'),
        ),
        migrations.AddField(
            model_name='tracepassingnetwork',
            name='to_player',
            field=models.ForeignKey(blank=True, help_text='Player who received the passes', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passing_network_to', to='tracevision.traceplayer'),
        ),
        migrations.AddField(
            model_name='traceplayer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='traceplayer',
            name='object_id',
            field=models.CharField(help_text='Unique identifier from TraceVision API', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='traceplayer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='traceplayer',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who owns this player data (optional for unmapped players)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trace_players', to='accounts.wajouser'),
        ),
        migrations.AddField(
            model_name='tracetouchleaderboard',
            name='player',
            field=models.ForeignKey(blank=True, help_text='Player this touch count belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='touch_leaderboard', to='tracevision.traceplayer'),
        ),
        migrations.AddField(
            model_name='tracevisionplayerstats',
            name='player',
            field=models.ForeignKey(blank=True, help_text='Player this statistics belong to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='tracevision.traceplayer'),
        ),
        migrations.AlterField(
            model_name='traceplayer',
            name='jersey_number',
            field=models.PositiveIntegerField(help_text="Player's jersey number"),
        ),
        migrations.AlterField(
            model_name='traceplayer',
            name='name',
            field=models.CharField(help_text="Player's name", max_length=100),
        ),
        migrations.AlterField(
            model_name='traceplayer',
            name='position',
            field=models.CharField(help_text="Player's position on the field", max_length=100),
        ),
        migrations.AlterField(
            model_name='traceplayer',
            name='session',
            field=models.ForeignKey(help_text='TraceVision session this player belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='trace_players', to='tracevision.tracesession'),
        ),
        migrations.AlterField(
            model_name='traceplayer',
            name='team',
            field=models.ForeignKey(help_text='Team this player belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='trace_players', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='tracesession',
            name='pitch_size',
            field=models.JSONField(blank=True, default=tracevision.models.get_default_pitch_size, help_text="Football field dimensions in meters: {'length': 105, 'width': 68}", null=True),
        ),
        migrations.AlterField(
            model_name='tracevisionplayerstats',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_player_stats', to='tracevision.tracesession'),
        ),
        migrations.AddIndex(
            model_name='traceclipreel',
            index=models.Index(fields=['session', 'player'], name='tracevision_session_a7906d_idx'),
        ),
        migrations.AddIndex(
            model_name='tracehighlight',
            index=models.Index(fields=['player', '-created_at'], name='tracevision_player__2680f7_idx'),
        ),
        migrations.AddIndex(
            model_name='tracehighlightobject',
            index=models.Index(fields=['player'], name='tracevision_player__93cb0d_idx'),
        ),
        migrations.AddIndex(
            model_name='traceobject',
            index=models.Index(fields=['player', 'type'], name='tracevision_player__d288e5_idx'),
        ),
        migrations.AddIndex(
            model_name='tracepass',
            index=models.Index(fields=['session', 'from_player', 'to_player'], name='tracevision_session_8955bf_idx'),
        ),
        migrations.AddIndex(
            model_name='traceplayer',
            index=models.Index(fields=['object_id'], name='tracevision_object__9971bd_idx'),
        ),
        migrations.AddIndex(
            model_name='traceplayer',
            index=models.Index(fields=['user'], name='tracevision_user_id_0361ed_idx'),
        ),
        migrations.AddIndex(
            model_name='traceplayer',
            index=models.Index(fields=['team'], name='tracevision_team_id_892a83_idx'),
        ),
        migrations.AddIndex(
            model_name='traceplayer',
            index=models.Index(fields=['session'], name='tracevision_session_17d54f_idx'),
        ),
        migrations.AddIndex(
            model_name='tracevisionplayerstats',
            index=models.Index(fields=['session', 'player'], name='tracevision_session_0ceddf_idx'),
        ),
        migrations.AddConstraint(
            model_name='traceplayer',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('object_id', 'user'), name='unique_object_id_per_user'),
        ),
        migrations.AddConstraint(
            model_name='traceplayer',
            constraint=models.UniqueConstraint(fields=('object_id', 'session'), name='unique_object_id_per_session'),
        ),
        migrations.RemoveField(
            model_name='tracepassingnetwork',
            name='from_object_id',
        ),
        migrations.RemoveField(
            model_name='tracepassingnetwork',
            name='to_object_id',
        ),
        migrations.RemoveField(
            model_name='tracetouchleaderboard',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='tracevisionplayerstats',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='traceclipreel',
            name='object_id',
        ),
    ]
