# Generated by Django 5.0.10 on 2025-12-30 13:18
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracevision', '0010_remove_traceplayer_tracevision_account_8c84c2_idx_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Drop the varchar_pattern_ops index that prevents type conversion
                migrations.RunSQL(
                    "DROP INDEX IF EXISTS tracevision_playerusermapping_mapped_by_id_a8745d35_like;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                # Change the column type from varchar(15) to uuid
                migrations.RunSQL(
                    "ALTER TABLE tracevision_playerusermapping ALTER COLUMN mapped_by_id TYPE uuid USING mapped_by_id::uuid;",
                    reverse_sql="ALTER TABLE tracevision_playerusermapping ALTER COLUMN mapped_by_id TYPE character varying(15) USING mapped_by_id::text;",
                ),
                # Add foreign key constraint if it doesn't exist
                migrations.RunSQL(
                    "ALTER TABLE tracevision_playerusermapping ADD CONSTRAINT tracevision_playerusermapping_mapped_by_id_fk FOREIGN KEY (mapped_by_id) REFERENCES accounts_wajouser(id) ON DELETE SET NULL;",
                    reverse_sql="ALTER TABLE tracevision_playerusermapping DROP CONSTRAINT IF EXISTS tracevision_playerusermapping_mapped_by_id_fk;",
                ),
            ],
            state_operations=[
                # No state operations needed as Django already knows the field type from the model
            ],
        ),
    ]
