# Generated by Django 5.0.10 on 2025-12-30 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracevision', '0010_remove_traceplayer_tracevision_account_8c84c2_idx_and_more'),
    ]

    operations = [
    ]
