# Generated by Django 5.0.10 on 2025-09-03 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracevision', '0011_alter_traceplayer_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='traceclipreel',
            name='tracevision_session_a7906d_idx',
        ),
        migrations.AlterUniqueTogether(
            name='traceclipreel',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='traceclipreel',
            name='bitrate',
            field=models.IntegerField(default=0, help_text='Video bitrate (kbps)'),
        ),
        migrations.AddField(
            model_name='traceclipreel',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the clip'),
        ),
        migrations.AddField(
            model_name='traceclipreel',
            name='frame_rate',
            field=models.IntegerField(default=30, help_text='Video frame rate (FPS)'),
        ),
        migrations.AddField(
            model_name='traceclipreel',
            name='generation_completed_at',
            field=models.DateTimeField(blank=True, help_text='When video generation completed', null=True),
        ),
        migrations.AddField(
            model_name='traceclipreel',
            name='generation_errors',
            field=models.JSONField(default=list, help_text='Any errors during generation'),
        ),
        migrations.AddField(
            model_name='traceclipreel',
            name='generation_metadata',
            field=models.JSONField(default=dict, help_text='Additional generation parameters and settings'),
        ),
        migrations.AddField(
            model_name='traceclipreel',
            name='generation_started_at',
            field=models.DateTimeField(blank=True, help_text='When video generation started', null=True),
        ),
        migrations.AddField(
            model_name='traceclipreel',
            name='generation_status',
            field=models.CharField(choices=[('pending', 'Pending Generation'), ('generating', 'Currently Generating'), ('completed', 'Generation Completed'), ('failed', 'Generation Failed'), ('skipped', 'Skipped')], default='pending', help_text='Status of video generation', max_length=20),
        ),
        migrations.AddField(
            model_name='traceclipreel',
            name='highlight',
            field=models.ForeignKey(help_text='The highlight this clip reel is based on', on_delete=django.db.models.deletion.CASCADE, related_name='clip_reels', to='tracevision.tracehighlight'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traceclipreel',
            name='involved_players',
            field=models.ManyToManyField(blank=True, help_text='All players involved in this highlight', related_name='involved_clip_reels', to='tracevision.traceplayer'),
        ),
        migrations.AddField(
            model_name='traceclipreel',
            name='primary_player',
            field=models.ForeignKey(blank=True, help_text='Primary player involved in this clip', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_clip_reels', to='tracevision.traceplayer'),
        ),
        migrations.AddField(
            model_name='traceclipreel',
            name='resolution',
            field=models.CharField(default='1080p', help_text='Video resolution', max_length=20),
        ),
        migrations.AddField(
            model_name='traceclipreel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='traceclipreel',
            name='video_duration_seconds',
            field=models.FloatField(default=0.0, help_text='Actual video duration in seconds'),
        ),
        migrations.AddField(
            model_name='traceclipreel',
            name='video_size_mb',
            field=models.FloatField(default=0.0, help_text='Video file size in MB'),
        ),
        migrations.AddField(
            model_name='traceclipreel',
            name='video_thumbnail_url',
            field=models.URLField(blank=True, help_text='Azure blob URL for video thumbnail'),
        ),
        migrations.AddField(
            model_name='traceclipreel',
            name='video_type',
            field=models.CharField(choices=[('original', 'Original (No Overlay)'), ('with_overlay', 'With Overlay'), ('zoomed_player', 'Zoomed on Player'), ('zoomed_team', 'Zoomed on Team'), ('tactical_view', 'Tactical View'), ('slow_motion', 'Slow Motion'), ('multi_angle', 'Multi-Angle')], default='original', help_text='Type of video variation', max_length=20),
        ),
        migrations.AddField(
            model_name='traceclipreel',
            name='video_url',
            field=models.URLField(blank=True, help_text='Azure blob URL for the generated video'),
        ),
        migrations.AddField(
            model_name='traceclipreel',
            name='video_variant_name',
            field=models.CharField(blank=True, help_text="Custom name for this video variant (e.g., 'Player Focus', 'Team View')", max_length=100),
        ),
        migrations.AlterField(
            model_name='traceclipreel',
            name='duration_ms',
            field=models.IntegerField(help_text='Duration in milliseconds'),
        ),
        migrations.AlterField(
            model_name='traceclipreel',
            name='end_clock',
            field=models.CharField(blank=True, help_text='End time in clock format', max_length=20),
        ),
        migrations.AlterField(
            model_name='traceclipreel',
            name='event_id',
            field=models.CharField(help_text='Unique event identifier', max_length=100),
        ),
        migrations.AlterField(
            model_name='traceclipreel',
            name='event_type',
            field=models.CharField(help_text='Type of event (touch, pass, etc.)', max_length=50),
        ),
        migrations.AlterField(
            model_name='traceclipreel',
            name='label',
            field=models.CharField(blank=True, help_text='Display label for the clip', max_length=100),
        ),
        migrations.AlterField(
            model_name='traceclipreel',
            name='side',
            field=models.CharField(help_text='Team side (home/away)', max_length=10),
        ),
        migrations.AlterField(
            model_name='traceclipreel',
            name='start_clock',
            field=models.CharField(blank=True, help_text='Start time in clock format', max_length=20),
        ),
        migrations.AlterField(
            model_name='traceclipreel',
            name='start_ms',
            field=models.IntegerField(help_text='Start time in milliseconds'),
        ),
        migrations.AlterField(
            model_name='traceclipreel',
            name='tags',
            field=models.JSONField(default=list, help_text='Tags for categorization and filtering'),
        ),
        migrations.AlterField(
            model_name='traceclipreel',
            name='video_stream',
            field=models.URLField(blank=True, help_text='Legacy video stream URL'),
        ),
        migrations.AddIndex(
            model_name='traceclipreel',
            index=models.Index(fields=['session', 'primary_player'], name='tracevision_session_8536ee_idx'),
        ),
        migrations.AddIndex(
            model_name='traceclipreel',
            index=models.Index(fields=['highlight', 'video_type'], name='tracevision_highlig_3c3e0d_idx'),
        ),
        migrations.AddIndex(
            model_name='traceclipreel',
            index=models.Index(fields=['generation_status', 'created_at'], name='tracevision_generat_932512_idx'),
        ),
        migrations.AddIndex(
            model_name='traceclipreel',
            index=models.Index(fields=['video_type', 'generation_status'], name='tracevision_video_t_b21c15_idx'),
        ),
        migrations.RemoveField(
            model_name='traceclipreel',
            name='player',
        ),
        migrations.RemoveField(
            model_name='traceclipreel',
            name='video_id',
        ),
    ]
