# Generated by Django 5.0.10 on 2025-09-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracevision', '0012_remove_traceclipreel_tracevision_session_a7906d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracesession',
            name='basic_game_stats',
            field=models.FileField(blank=True, help_text='Basic game stats file', null=True, upload_to='basic_game_stats/'),
        ),
        migrations.AddField(
            model_name='tracesession',
            name='first_half_end_time',
            field=models.CharField(blank=True, help_text="First half end time in format 'HH:MM:SS'", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tracesession',
            name='match_end_time',
            field=models.CharField(blank=True, help_text="Match end time in format 'HH:MM:SS'", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tracesession',
            name='match_start_time',
            field=models.CharField(blank=True, help_text="Match start time in format 'HH:MM:SS'", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tracesession',
            name='second_half_start_time',
            field=models.CharField(blank=True, help_text="Second half start time in format 'HH:MM:SS'", max_length=20, null=True),
        ),
    ]
