# Generated by Django 5.0.10 on 2025-09-15 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracevision', '0013_tracesession_basic_game_stats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracehighlight',
            name='event_metadata',
            field=models.JSONField(default=dict, help_text='Additional event-specific data (scorer, card type, etc.)'),
        ),
        migrations.AddField(
            model_name='tracehighlight',
            name='event_type',
            field=models.CharField(choices=[('touch', 'Touch'), ('touch-chain', 'Touch Chain'), ('goal', 'Goal'), ('yellow_card', 'Yellow Card'), ('red_card', 'Red Card'), ('substitution', 'Substitution'), ('save', 'Save'), ('shot', 'Shot'), ('pass', 'Pass'), ('tackle', 'Tackle'), ('foul', 'Foul'), ('offside', 'Offside'), ('corner', 'Corner'), ('free_kick', 'Free Kick'), ('penalty', 'Penalty'), ('other', 'Other')], default='touch', help_text='Type of event this highlight represents', max_length=20),
        ),
        migrations.AddField(
            model_name='tracehighlight',
            name='half',
            field=models.PositiveIntegerField(blank=True, help_text='Match half (1 or 2) when event occurred', null=True),
        ),
        migrations.AddField(
            model_name='tracehighlight',
            name='match_time',
            field=models.CharField(blank=True, help_text="Match time when event occurred in MM:SS format (e.g., '16:30', '77:15')", max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='tracehighlight',
            name='performance_impact',
            field=models.FloatField(default=0.0, help_text='Impact score on player performance (0-100)'),
        ),
        migrations.AddField(
            model_name='tracehighlight',
            name='source',
            field=models.CharField(choices=[('tracevision', 'TraceVision API'), ('excel_import', 'Excel Import'), ('manual', 'Manual Entry'), ('ai_detection', 'AI Detection')], default='tracevision', help_text='Source of this highlight data', max_length=20),
        ),
        migrations.AddField(
            model_name='tracehighlight',
            name='team_impact',
            field=models.FloatField(default=0.0, help_text='Impact score on team performance (0-100)'),
        ),
        migrations.AddIndex(
            model_name='tracehighlight',
            index=models.Index(fields=['event_type', 'session'], name='tracevision_event_t_9ae343_idx'),
        ),
        migrations.AddIndex(
            model_name='tracehighlight',
            index=models.Index(fields=['source', 'session'], name='tracevision_source_2cbf05_idx'),
        ),
        migrations.AddIndex(
            model_name='tracehighlight',
            index=models.Index(fields=['match_time', 'session'], name='tracevision_match_t_e0fc66_idx'),
        ),
        migrations.AddIndex(
            model_name='tracehighlight',
            index=models.Index(fields=['performance_impact', 'session'], name='tracevision_perform_3276a5_idx'),
        ),
    ]
