# Generated by Django 5.0.4 on 2024-11-24 14:09

import games.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=10, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("match", "Match"), ("training", "Training")],
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Game",
                "verbose_name_plural": "Games",
            },
        ),
        migrations.CreateModel(
            name="GameGPSData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_file",
                    models.FileField(
                        upload_to=games.models.game_gps_data_file_path,
                        validators=[games.models.validate_file_extension],
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("is_processed", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Game GPS Data",
                "verbose_name_plural": "Game GPS Data",
            },
        ),
        migrations.CreateModel(
            name="GameVideoData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(choices=[("BEPRO", "BEPRO")], max_length=16),
                ),
                (
                    "data_file",
                    models.FileField(
                        upload_to=games.models.game_video_data_file_path,
                        validators=[games.models.validate_file_extension],
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("is_processed", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Game Video Data",
                "verbose_name_plural": "Game Video Data",
            },
        ),
    ]
