# Generated by Django 5.0.10 on 2026-01-06 12:37

import games.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameGPSData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('game_type', models.CharField(choices=[('match', 'Match'), ('training', 'Training')], max_length=10)),
                ('data_file', models.FileField(upload_to=games.models.game_gps_data_file_path, validators=[games.models.validate_file_extension])),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Game GPS Data',
                'verbose_name_plural': 'Game GPS Data',
            },
        ),
        migrations.CreateModel(
            name='GameMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('data', models.JSONField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Game Meta Data JSON',
                'verbose_name_plural': 'Game Meta Data JSON',
            },
        ),
        migrations.CreateModel(
            name='GameUserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Game User Role',
                'verbose_name_plural': 'Game User Roles',
            },
        ),
        migrations.CreateModel(
            name='GameVideoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.CharField(choices=[('BEPRO', 'BEPRO')], max_length=16)),
                ('game_type', models.CharField(choices=[('match', 'Match'), ('training', 'Training')], max_length=10)),
                ('data_file', models.FileField(upload_to=games.models.game_video_data_file_path, validators=[games.models.validate_file_extension])),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('first_half_url', models.TextField()),
                ('first_half_padding', models.FloatField(default=0.0, verbose_name='First Half Padding (Seconds)')),
                ('second_half_url', models.TextField()),
                ('second_half_padding', models.FloatField(default=0.0, verbose_name='Second Half Padding (Seconds)')),
                ('start_time_padding', models.FloatField(default=0.0, verbose_name='Start Time Padding (Seconds)')),
                ('end_time_padding', models.FloatField(default=0.0, verbose_name='End Time Padding (Seconds)')),
                ('highlights_url', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Game Video Data',
                'verbose_name_plural': 'Game Video Data',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[('match', 'Match'), ('training', 'Training')], max_length=10)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('language_metadata', models.JSONField(blank=True, default=dict, help_text="Multilingual match data with 'en' and 'he' sections containing match summary, lineups, replacements, bench, coaches, and referees", null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('referees', models.ManyToManyField(blank=True, limit_choices_to={'role': 'Referee'}, related_name='games_refereed', to='accounts.wajouser')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
            },
        ),
    ]
