# Generated by Django 5.0.4 on 2024-11-24 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("games", "0001_initial"),
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="teams",
            field=models.ManyToManyField(
                blank=True, related_name="games", to="teams.team"
            ),
        ),
        migrations.AddField(
            model_name="gamegpsdata",
            name="game",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gps_data",
                to="games.game",
            ),
        ),
        migrations.AddField(
            model_name="gamevideodata",
            name="game",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="video_data",
                to="games.game",
            ),
        ),
    ]
