# Generated by Django 5.0.10 on 2026-01-06 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('games', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='games', to='teams.team'),
        ),
        migrations.AddField(
            model_name='gamegpsdata',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gps_data', to='games.game'),
        ),
        migrations.AddField(
            model_name='gamemetadata',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_meta_data', to='games.game'),
        ),
        migrations.AddField(
            model_name='gameuserrole',
            name='game',
            field=models.ForeignKey(help_text='Game this user is linked to', on_delete=django.db.models.deletion.CASCADE, related_name='game_roles', to='games.game'),
        ),
        migrations.AddField(
            model_name='gameuserrole',
            name='user',
            field=models.ForeignKey(help_text='User linked to this game', on_delete=django.db.models.deletion.CASCADE, related_name='game_roles', to='accounts.wajouser'),
        ),
        migrations.AddField(
            model_name='gamevideodata',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_data', to='games.game'),
        ),
        migrations.AddIndex(
            model_name='gameuserrole',
            index=models.Index(fields=['game', 'user'], name='games_gameu_game_id_2eb297_idx'),
        ),
        migrations.AddIndex(
            model_name='gameuserrole',
            index=models.Index(fields=['user'], name='games_gameu_user_id_9c77a5_idx'),
        ),
        migrations.AddIndex(
            model_name='gameuserrole',
            index=models.Index(fields=['game'], name='games_gameu_game_id_4b44db_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gameuserrole',
            unique_together={('game', 'user')},
        ),
    ]
