# Generated by Django 5.0.10 on 2026-01-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_info',
            field=models.JSONField(blank=True, default=dict, help_text="Detailed game information in multilingual format. Structure: {'en': {'home': {...}, 'away': {...}}, 'he': {'home': {...}, 'away': {...}}}. Each team contains: total_score, first_half_score, second_half_score, goals (array with player_name, jersey, half, goaltime), starting_lineups, replacements, coaches, referees", null=True),
        ),
    ]
