# Generated by Django 5.0.4 on 2024-11-25 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamegpsdata",
            name="game_type",
            field=models.CharField(
                choices=[("match", "Match"), ("training", "Training")],
                default="Match",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="gamevideodata",
            name="game_type",
            field=models.CharField(
                choices=[("match", "Match"), ("training", "Training")],
                default="Match",
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
