# Generated by Django 5.0.10 on 2024-12-12 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0003_gamegpsdata_game_type_gamevideodata_game_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gamegpsdata",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gamevideodata",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
