# Generated by Django 5.0.10 on 2024-12-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0004_game_deleted_at_gamegpsdata_deleted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamevideodata",
            name="first_half_padding",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="gamevideodata",
            name="first_half_url",
            field=models.TextField(
                default="https://hiwajovideov2.azureedge.net/videos/Jul 7, 2024 Haifa Goldshinfeld vs Bnei Sakhnin 1st Half.mp4"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="gamevideodata",
            name="highlight_url",
            field=models.TextField(
                default="https://hiwajovideov2.azureedge.net/videos/Jul 7, 2024 Haifa Goldshinfeld vs Bnei Sakhnin Highlights_2024-08-23_21-52-47.mp4"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="gamevideodata",
            name="second_half_padding",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="gamevideodata",
            name="second_half_url",
            field=models.TextField(
                default="https://hiwajovideov2.azureedge.net/videos/Jul 7, 2024 Haifa Goldshinfeld vs Bnei Sakhnin 2nd Half.mp4"
            ),
            preserve_default=False,
        ),
    ]
