# Generated by Django 5.0.10 on 2024-12-14 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0005_gamevideodata_first_half_padding_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameMetaData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("data", models.JSONField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "game",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="game_meta_data",
                        to="games.game",
                    ),
                ),
            ],
            options={
                "verbose_name": "Game Meta Data JSON",
                "verbose_name_plural": "Game Meta Data JSON",
            },
        ),
    ]
