# Generated by Django 5.0.10 on 2024-12-18 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0006_gamemetadata"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gamevideodata",
            old_name="highlight_url",
            new_name="highlights_url",
        ),
    ]
