# Generated by Django 5.0.10 on 2025-01-14 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0007_rename_highlight_url_gamevideodata_highlights_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamevideodata",
            name="end_time_padding",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="gamevideodata",
            name="start_time_padding",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="gamevideodata",
            name="first_half_padding",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="gamevideodata",
            name="second_half_padding",
            field=models.FloatField(default=0.0),
        ),
    ]
