# Generated by Django 5.0.10 on 2025-06-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_gamevideodata_end_time_padding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamevideodata',
            name='end_time_padding',
            field=models.FloatField(default=0.0, verbose_name='End Time Padding (Seconds)'),
        ),
        migrations.AlterField(
            model_name='gamevideodata',
            name='first_half_padding',
            field=models.FloatField(default=0.0, verbose_name='First Half Padding (Seconds)'),
        ),
        migrations.AlterField(
            model_name='gamevideodata',
            name='second_half_padding',
            field=models.FloatField(default=0.0, verbose_name='Second Half Padding (Seconds)'),
        ),
        migrations.AlterField(
            model_name='gamevideodata',
            name='start_time_padding',
            field=models.FloatField(default=0.0, verbose_name='Start Time Padding (Seconds)'),
        ),
    ]
