# Generated by Django 5.0.10 on 2025-11-21 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_wajouser_team"),
        ("games", "0009_alter_gamevideodata_end_time_padding_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameUserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        help_text="User's role in this game (uses WajoUser.role values: Player, Coach, Private Coach, etc.)",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "game",
                    models.ForeignKey(
                        help_text="Game this user is linked to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_roles",
                        to="games.game",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User linked to this game",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_roles",
                        to="accounts.wajouser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Game User Role",
                "verbose_name_plural": "Game User Roles",
                "indexes": [
                    models.Index(
                        fields=["game", "user"], name="games_gameu_game_id_2eb297_idx"
                    ),
                    models.Index(
                        fields=["user"], name="games_gameu_user_id_9c77a5_idx"
                    ),
                    models.Index(
                        fields=["game"], name="games_gameu_game_id_4b44db_idx"
                    ),
                ],
                "unique_together": {("game", "user")},
            },
        ),
    ]
