# Generated by Django 5.0.10 on 2025-11-21 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0010_gameuserrole"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GameUserRole",
        ),
    ]
