# Generated by Django 5.0.10 on 2025-11-28 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_gameuserrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameuserrole',
            name='role',
        ),
    ]
