# Generated by Django 5.0.10 on 2025-12-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_wajouser_country_wajouser_country_code_and_more'),
        ('games', '0014_game_language_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='referees',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'Referee'}, related_name='games_refereed', to='accounts.wajouser'),
        ),
    ]
