# Generated by Django 5.0.4 on 2024-11-23 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OnboardingStep",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="onboarding_step",
                        serialize=False,
                        to="accounts.wajouser",
                    ),
                ),
                ("step", models.CharField(default="PQ1", max_length=10)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Onboarding Flow",
                "verbose_name_plural": "Onboarding Flow",
            },
        ),
    ]
