# Generated by Django 5.0.10 on 2025-12-30 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_onboardingstep_deleted_at'),
    ]

    operations = [
    ]
