# Generated by Django 5.0.10 on 2025-12-30 13:17
# Fixed on 2026-01-04 to properly convert user_id from varchar(15) to uuid

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_onboardingstep_deleted_at'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Drop the varchar_pattern_ops index that prevents type conversion
                migrations.RunSQL(
                    "DROP INDEX IF EXISTS onboarding_onboardingstep_user_id_57b5db13_like;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                # Drop the primary key constraint first
                migrations.RunSQL(
                    "ALTER TABLE onboarding_onboardingstep DROP CONSTRAINT IF EXISTS onboarding_onboardingstep_pkey CASCADE;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                # Change the column type from varchar(15) to uuid
                migrations.RunSQL(
                    "ALTER TABLE onboarding_onboardingstep ALTER COLUMN user_id TYPE uuid USING user_id::uuid;",
                    reverse_sql="ALTER TABLE onboarding_onboardingstep ALTER COLUMN user_id TYPE character varying(15) USING user_id::text;",
                ),
                # Re-add the primary key constraint
                migrations.RunSQL(
                    "ALTER TABLE onboarding_onboardingstep ADD PRIMARY KEY (user_id);",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                # Re-add the foreign key constraint
                migrations.RunSQL(
                    "ALTER TABLE onboarding_onboardingstep ADD CONSTRAINT onboarding_onboardingstep_user_id_fk FOREIGN KEY (user_id) REFERENCES accounts_wajouser(id) ON DELETE CASCADE;",
                    reverse_sql="ALTER TABLE onboarding_onboardingstep DROP CONSTRAINT IF EXISTS onboarding_onboardingstep_user_id_fk;",
                ),
            ],
            state_operations=[
                # No state operations needed as Django already knows the field type from the model
            ],
        ),
    ]
