# Generated by Django 5.0.10 on 2026-01-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_fix_user_id_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingstep',
            name='step',
            field=models.CharField(default='PQ1', max_length=15),
        ),
    ]
