# Generated by Django 5.0.10 on 2025-03-08 09:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beproeventdata',
            options={'verbose_name': 'Bepro Event Data', 'verbose_name_plural': 'Bepro Event Data'},
        ),
        migrations.RemoveField(
            model_name='beproeventdata',
            name='assist',
        ),
        migrations.RemoveField(
            model_name='beproeventdata',
            name='ball_position_x',
        ),
        migrations.RemoveField(
            model_name='beproeventdata',
            name='ball_position_y',
        ),
        migrations.RemoveField(
            model_name='beproeventdata',
            name='body_part',
        ),
        migrations.RemoveField(
            model_name='beproeventdata',
            name='cross',
        ),
        migrations.RemoveField(
            model_name='beproeventdata',
            name='event_period',
        ),
        migrations.RemoveField(
            model_name='beproeventdata',
            name='event_time',
        ),
        migrations.RemoveField(
            model_name='beproeventdata',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='beproeventdata',
            name='key_pass',
        ),
        migrations.RemoveField(
            model_name='beproeventdata',
            name='match_id',
        ),
        migrations.RemoveField(
            model_name='beproeventdata',
            name='outcome',
        ),
        migrations.RemoveField(
            model_name='beproeventdata',
            name='player_id',
        ),
        migrations.RemoveField(
            model_name='beproeventdata',
            name='record_id',
        ),
        migrations.RemoveField(
            model_name='beproeventdata',
            name='relative_event_id',
        ),
        migrations.RemoveField(
            model_name='beproeventdata',
            name='relative_event_x',
        ),
        migrations.RemoveField(
            model_name='beproeventdata',
            name='relative_event_y',
        ),
        migrations.RemoveField(
            model_name='beproeventdata',
            name='sub_event_type',
        ),
        migrations.RemoveField(
            model_name='beproeventdata',
            name='team_id',
        ),
        migrations.RemoveField(
            model_name='beproeventdata',
            name='x',
        ),
        migrations.RemoveField(
            model_name='beproeventdata',
            name='xg',
        ),
        migrations.RemoveField(
            model_name='beproeventdata',
            name='y',
        ),
        migrations.AddField(
            model_name='beproeventdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beproeventdata',
            name='event',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beproeventdata',
            name='event_hebrew',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='beproeventdata',
            name='event_sub_event',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='beproeventdata',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beproeventdata',
            name='explanation_hebrew',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beproeventdata',
            name='match',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='match_data.bepromatchdata'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beproeventdata',
            name='reference',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beproeventdata',
            name='sub_event_hebrew',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='beproeventdata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='beproeventdata',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='beproformationdata',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0df72732-140a-4270-bed6-f4bc3f7c32a1'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='beproleaguedetail',
            name='id',
            field=models.UUIDField(default=uuid.UUID('478d4460-f9bd-4c69-864d-ec7dbd843a9f'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='beprolineup',
            name='id',
            field=models.UUIDField(default=uuid.UUID('49b5e7e9-2a59-4f54-b526-8982bcff8671'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bepromatchdata',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7bb364e6-d384-41e9-86ea-d62fa791f55d'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bepromatchdetail',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ded40348-6817-41c7-a474-ddb3e463fc05'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='beprophysicaleventdata',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc75792f-f0ed-4c6b-afc7-4a5ebe1c0f43'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='beproplayer',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3513bf3b-d3fc-4283-8c66-b843c8828ea3'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='beproplayerstat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('089f6e25-f4b8-4388-994c-e25a07825489'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='beproplayerstatsextended',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c635bfad-b9e3-4317-8c3f-80ba9e6414d7'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='beproseason',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ae7c58d3-da7e-42a2-81cf-716e6c13e46c'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='beprosequencedata',
            name='id',
            field=models.UUIDField(default=uuid.UUID('08403162-6808-4d36-ade9-418b5ac4f77b'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='beproteamstat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('77db0ffa-cf3e-441b-9842-2b1c7902218c'), primary_key=True, serialize=False),
        ),
    ]
