# Generated by Django 5.0.10 on 2025-03-08 10:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_data', '0002_alter_beproeventdata_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beproeventdata',
            old_name='match',
            new_name='match_id',
        ),
        migrations.AlterField(
            model_name='beproformationdata',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c7cc7054-813c-4fa0-924e-33c84f861b4d'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='beproleaguedetail',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d061a007-6205-4736-a580-85f0b584fb10'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='beprolineup',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0e765f2d-a192-4a75-a1da-2247e473a787'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bepromatchdata',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6f590614-8c58-4cfe-80c5-995f81cccf98'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bepromatchdetail',
            name='id',
            field=models.UUIDField(default=uuid.UUID('20c404aa-59df-4aec-afb0-498923f3df58'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='beprophysicaleventdata',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a962440f-e71d-471f-8cd4-4c27c850aece'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='beproplayer',
            name='id',
            field=models.UUIDField(default=uuid.UUID('dd5d3353-bfa2-4fbb-85c5-c26ee6f023fb'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='beproplayerstat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('913b0ee7-1284-4750-9200-7e12b74424a5'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='beproplayerstatsextended',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b4b5d629-ff69-4f91-9074-ad259ec31c34'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='beproseason',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6f76e1d6-a39c-4161-bcb7-11d8a40c0379'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='beprosequencedata',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5811c6a5-b991-4783-bc34-0a651a1329ab'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='beproteamstat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c99281ea-bdf0-4052-af78-e0be7cf9e80d'), primary_key=True, serialize=False),
        ),
    ]
