# Generated by Django 5.0.10 on 2025-03-27 05:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_data', '0002_alter_beproformationdata_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchSummaryStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_json', models.JSONField()),
            ],
        )
    ]
