# Generated by Django 5.0.10 on 2025-07-21 10:11

import match_data.models.generic
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_data', '0006_alter_beproformationdata_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelfile',
            name='file',
            field=models.FileField(upload_to=match_data.models.generic.match_data_file_path, validators=[match_data.models.generic.validate_excel_file]),
        ),
    ]