# Generated by Django 5.0.10 on 2026-01-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttackingSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metrics', models.JSONField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Attacking Skills',
                'verbose_name_plural': 'Attacking Skills',
            },
        ),
        migrations.CreateModel(
            name='GPSAthleticSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metrics', models.JSONField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GPS-Athletic Skills',
                'verbose_name_plural': 'GPS-Athletic Skills',
            },
        ),
        migrations.CreateModel(
            name='GPSFootballAbilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metrics', models.JSONField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GPS-Football Abilities',
                'verbose_name_plural': 'GPS-Football Abilities',
            },
        ),
        migrations.CreateModel(
            name='GreetingCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('text', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Greetings Cache',
                'verbose_name_plural': 'Greetings Cache',
            },
        ),
        migrations.CreateModel(
            name='InsightCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('card', models.CharField(max_length=64)),
                ('text', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Insights Cache',
                'verbose_name_plural': 'Insights Cache',
            },
        ),
        migrations.CreateModel(
            name='NewsCardData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('he', 'Hebrew')], default='en', max_length=10)),
                ('title', models.CharField(max_length=128)),
                ('data', models.JSONField()),
                ('highlights', models.JSONField(default=dict)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'News Card Data (JSON)',
                'verbose_name_plural': 'News Card Data (JSON)',
            },
        ),
        migrations.CreateModel(
            name='RPEMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metrics', models.JSONField(default=dict)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'RPE Metrics',
                'verbose_name_plural': 'RPE Metrics',
            },
        ),
        migrations.CreateModel(
            name='StatusCardMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metrics', models.JSONField(default=dict)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Status Card Metrics',
                'verbose_name_plural': 'Status Card Metrics',
            },
        ),
        migrations.CreateModel(
            name='TrainingCardData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('he', 'Hebrew')], default='en', max_length=10)),
                ('first_dropdown', models.CharField(max_length=128)),
                ('second_dropdown', models.CharField(max_length=128)),
                ('topic', models.CharField(blank=True, max_length=128, null=True)),
                ('video_link', models.TextField(blank=True, null=True)),
                ('_type', models.CharField(blank=True, max_length=128, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Training Card Data (JSON)',
                'verbose_name_plural': 'Training Card Data (JSON)',
            },
        ),
        migrations.CreateModel(
            name='VideoCardDefensive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metrics', models.JSONField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Video Card Defensive',
                'verbose_name_plural': 'Video Card Defensive',
            },
        ),
        migrations.CreateModel(
            name='VideoCardDistributions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metrics', models.JSONField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Video Card Distributions',
                'verbose_name_plural': 'Video Card Distributions',
            },
        ),
    ]
