# Generated by Django 5.0.4 on 2024-11-23 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttackingSkills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metrics", models.JSONField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attacking_skills",
                        to="accounts.wajouser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attacking Skills",
                "verbose_name_plural": "Attacking Skills",
            },
        ),
        migrations.CreateModel(
            name="DefensivePerformanceMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metrics", models.JSONField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="difensive_performance_metrics",
                        to="accounts.wajouser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Defensive Performance Metrics",
                "verbose_name_plural": "Defensive Performance Metrics",
            },
        ),
        migrations.CreateModel(
            name="GameStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metrics", models.JSONField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_stats",
                        to="accounts.wajouser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Game Stats",
                "verbose_name_plural": "Game Stats",
            },
        ),
        migrations.CreateModel(
            name="OffensivePerformanceMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metrics", models.JSONField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offensive_performance_metrics",
                        to="accounts.wajouser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Offensive Performance Metrics",
                "verbose_name_plural": "Offensive Performance Metrics",
            },
        ),
        migrations.CreateModel(
            name="StatusCardMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metrics", models.JSONField(default=dict)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_card_metrics",
                        to="accounts.wajouser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Status Card Metrics",
                "verbose_name_plural": "Status Card Metrics",
            },
        ),
        migrations.CreateModel(
            name="VideoCardDefensive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metrics", models.JSONField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videocard_defensive",
                        to="accounts.wajouser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Video Card Defensive",
                "verbose_name_plural": "Video Card Defensive",
            },
        ),
        migrations.CreateModel(
            name="VideoCardDistributions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metrics", models.JSONField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videocard_distributions",
                        to="accounts.wajouser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Video Card Distributions",
                "verbose_name_plural": "Video Card Distributions",
            },
        ),
    ]
