# Generated by Django 5.0.4 on 2024-11-24 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("games", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttackingSkills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metrics", models.JSONField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_attacking_skills",
                        to="games.game",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attacking_skills",
                        to="accounts.wajouser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attacking Skills",
                "verbose_name_plural": "Attacking Skills",
            },
        ),
        migrations.CreateModel(
            name="GPSAthleticSkills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metrics", models.JSONField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_athletic_skills",
                        to="games.game",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="athletic_skills",
                        to="accounts.wajouser",
                    ),
                ),
            ],
            options={
                "verbose_name": "GPS-Athletic Skills",
                "verbose_name_plural": "GPS-Athletic Skills",
            },
        ),
        migrations.CreateModel(
            name="GPSFootballAbilities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metrics", models.JSONField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_gps_football_abilities",
                        to="games.game",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gps_football_abilities",
                        to="accounts.wajouser",
                    ),
                ),
            ],
            options={
                "verbose_name": "GPS-Football Abilities",
                "verbose_name_plural": "GPS-Football Abilities",
            },
        ),
        migrations.CreateModel(
            name="StatusCardMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metrics", models.JSONField(default=dict)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_status_card_metrics",
                        to="games.game",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_card_metrics",
                        to="accounts.wajouser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Status Card Metrics",
                "verbose_name_plural": "Status Card Metrics",
            },
        ),
        migrations.CreateModel(
            name="VideoCardDefensive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metrics", models.JSONField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_videocard_defensive",
                        to="games.game",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videocard_defensive",
                        to="accounts.wajouser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Video Card Defensive",
                "verbose_name_plural": "Video Card Defensive",
            },
        ),
        migrations.CreateModel(
            name="VideoCardDistributions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metrics", models.JSONField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_videocard_distributions",
                        to="games.game",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videocard_distributions",
                        to="accounts.wajouser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Video Card Distributions",
                "verbose_name_plural": "Video Card Distributions",
            },
        ),
    ]
