# Generated by Django 5.0.4 on 2024-11-25 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="statuscardmetrics",
            name="game",
        ),
    ]
