# Generated by Django 5.0.4 on 2024-11-24 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("cards", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gamestats",
            name="user",
        ),
        migrations.RemoveField(
            model_name="offensiveperformancemetrics",
            name="user",
        ),
        migrations.CreateModel(
            name="GPSAthleticSkills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metrics", models.JSONField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="athletic_skills",
                        to="accounts.wajouser",
                    ),
                ),
            ],
            options={
                "verbose_name": "GPS-Athletic Skills",
                "verbose_name_plural": "GPS-Athletic Skills",
            },
        ),
        migrations.CreateModel(
            name="GPSFootballAbilities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metrics", models.JSONField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gps_football_abilities",
                        to="accounts.wajouser",
                    ),
                ),
            ],
            options={
                "verbose_name": "GPS-Football Abilities",
                "verbose_name_plural": "GPS-Football Abilities",
            },
        ),
        migrations.DeleteModel(
            name="DefensivePerformanceMetrics",
        ),
        migrations.DeleteModel(
            name="GameStats",
        ),
        migrations.DeleteModel(
            name="OffensivePerformanceMetrics",
        ),
    ]
