# Generated by Django 5.0.10 on 2026-01-06 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('cards', '0001_initial'),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attackingskills',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_attacking_skills', to='games.game'),
        ),
        migrations.AddField(
            model_name='attackingskills',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attacking_skills', to='accounts.wajouser'),
        ),
        migrations.AddField(
            model_name='gpsathleticskills',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_athletic_skills', to='games.game'),
        ),
        migrations.AddField(
            model_name='gpsathleticskills',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athletic_skills', to='accounts.wajouser'),
        ),
        migrations.AddField(
            model_name='gpsfootballabilities',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_gps_football_abilities', to='games.game'),
        ),
        migrations.AddField(
            model_name='gpsfootballabilities',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_football_abilities', to='accounts.wajouser'),
        ),
        migrations.AddField(
            model_name='greetingcache',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='greetings_cache', to='accounts.wajouser'),
        ),
        migrations.AddField(
            model_name='insightcache',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights_cache', to='accounts.wajouser'),
        ),
        migrations.AddField(
            model_name='rpemetrics',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rpe_metrics', to='accounts.wajouser'),
        ),
        migrations.AddField(
            model_name='statuscardmetrics',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_card_metrics', to='accounts.wajouser'),
        ),
        migrations.AddField(
            model_name='videocarddefensive',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_videocard_defensive', to='games.game'),
        ),
        migrations.AddField(
            model_name='videocarddefensive',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videocard_defensive', to='accounts.wajouser'),
        ),
        migrations.AddField(
            model_name='videocarddistributions',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_videocard_distributions', to='games.game'),
        ),
        migrations.AddField(
            model_name='videocarddistributions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videocard_distributions', to='accounts.wajouser'),
        ),
    ]
