# Generated by Django 5.0.4 on 2024-11-25 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("cards", "0002_remove_statuscardmetrics_game"),
    ]

    operations = [
        migrations.CreateModel(
            name="RPEMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metrics", models.JSONField(default=dict)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rpe_metrics",
                        to="accounts.wajouser",
                    ),
                ),
            ],
            options={
                "verbose_name": "RPE Metrics",
                "verbose_name_plural": "RPE Metrics",
            },
        ),
    ]
