# Generated by Django 5.1.4 on 2024-12-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0003_rpemetrics"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingCardData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_dropdown", models.CharField(max_length=64)),
                ("second_dropdown", models.CharField(max_length=64)),
                ("topic", models.CharField(max_length=64)),
                ("video_link", models.TextField()),
                ("_type", models.CharField(max_length=64)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "GPS-Football Abilities",
                "verbose_name_plural": "GPS-Football Abilities",
            },
        ),
    ]
