# Generated by Django 5.1.4 on 2024-12-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0004_trainingcarddata"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trainingcarddata",
            options={
                "verbose_name": "Training Card Data (JSON)",
                "verbose_name_plural": "Training Card Data (JSON)",
            },
        ),
        migrations.AlterField(
            model_name="trainingcarddata",
            name="_type",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="trainingcarddata",
            name="topic",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="trainingcarddata",
            name="video_link",
            field=models.TextField(blank=True, null=True),
        ),
    ]
