# Generated by Django 5.1.4 on 2024-12-10 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0005_alter_trainingcarddata_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsCardData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("data", models.JSONField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "News Card Data (JSON)",
                "verbose_name_plural": "News Card Data (JSON)",
            },
        ),
        migrations.AlterField(
            model_name="trainingcarddata",
            name="_type",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="trainingcarddata",
            name="first_dropdown",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="trainingcarddata",
            name="second_dropdown",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="trainingcarddata",
            name="topic",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
