# Generated by Django 5.0.10 on 2024-12-12 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0006_newscarddata_alter_trainingcarddata__type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rpemetrics",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
