# Generated by Django 5.0.10 on 2024-12-12 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0007_rpemetrics_deleted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="attackingskills",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gpsathleticskills",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gpsfootballabilities",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="newscarddata",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="statuscardmetrics",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trainingcarddata",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="videocarddefensive",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="videocarddistributions",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
