# Generated by Django 5.0.10 on 2024-12-22 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_otpstore_deleted_at_and_more"),
        ("cards", "0008_attackingskills_deleted_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GreetingCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("text", models.TextField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="greetings_cache",
                        to="accounts.wajouser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Greetings Cache",
                "verbose_name_plural": "Greetings Cache",
            },
        ),
        migrations.CreateModel(
            name="InsightCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("text", models.TextField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insights_cache",
                        to="accounts.wajouser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Insights Cache",
                "verbose_name_plural": "Insights Cache",
            },
        ),
    ]
