# Generated by Django 5.0.10 on 2024-12-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0009_greetingcache_insightcache"),
    ]

    operations = [
        migrations.AddField(
            model_name="insightcache",
            name="card",
            field=models.CharField(default="StatusCard", max_length=64),
            preserve_default=False,
        ),
    ]
