# Generated by Django 5.0.10 on 2025-07-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_insightcache_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscarddata',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('he', 'Hebrew')], default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='trainingcarddata',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('he', 'Hebrew')], default='en', max_length=10),
        ),
    ]
