# Generated by Django 5.0.10 on 2025-07-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_newscarddata_language_trainingcarddata_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscarddata',
            name='highlights',
            field=models.JSONField(default=dict),
        ),
    ]
