name: Deploy to Azure Container Apps (Production)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Container Registry
      run: |
        echo "${{ secrets.CONTAINER_REGISTRY_PASSWORD }}" | docker login ${{ secrets.CONTAINER_REGISTRY_USERNAME }}.azurecr.io -u ${{ secrets.CONTAINER_REGISTRY_USERNAME }} --password-stdin
    
    - name: Build and Push Docker Image
      run: |
        IMAGE_NAME=${{ secrets.CONTAINER_REGISTRY_USERNAME }}.azurecr.io/${{ secrets.WAJO_BACKEND_CONTAINER_PRODUCTION_NAME }}:${{ github.sha }}
        docker build -t $IMAGE_NAME .
        docker push $IMAGE_NAME

    - name: Deploy to ACA
      run: |
        IMAGE_NAME=${{ secrets.CONTAINER_REGISTRY_USERNAME }}.azurecr.io/${{ secrets.WAJO_BACKEND_CONTAINER_PRODUCTION_NAME }}:${{ github.sha }}
        az containerapp update --name ${{ secrets.AZURE_ACA_PRODUCTION_NAME }} \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --image $IMAGE_NAME

    - name: Cleanup old Docker images
      run: |
        # Keep only the last 3 images and delete older ones
        PURGE_CMD="acr purge --filter '${{ secrets.WAJO_BACKEND_CONTAINER_PRODUCTION_NAME }}:.*' --ago 0d --keep 3 --untagged"
        az acr run --cmd "$PURGE_CMD" --registry ${{ secrets.CONTAINER_REGISTRY_USERNAME }} /dev/null