name: Deploy to Azure Container Apps (Staging)

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
          fetch-depth: 0

    # - name: SonarQube Scan
    #   uses: SonarSource/sonarqube-scan-action@v4
    #   env:
    #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    #     SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Container Registry
      run: |
        echo "${{ secrets.CONTAINER_REGISTRY_PASSWORD }}" | docker login ${{ secrets.CONTAINER_REGISTRY_USERNAME }}.azurecr.io -u ${{ secrets.CONTAINER_REGISTRY_USERNAME }} --password-stdin
    
    - name: Build and Push Docker Image
      run: |
        IMAGE_NAME=${{ secrets.CONTAINER_REGISTRY_USERNAME }}.azurecr.io/${{ secrets.WAJO_BACKEND_CONTAINER_STAGING_NAME }}:${{ github.sha }}
        docker build -t $IMAGE_NAME .
        docker push $IMAGE_NAME

    - name: Deploy to ACA
      run: |
        IMAGE_NAME=${{ secrets.CONTAINER_REGISTRY_USERNAME }}.azurecr.io/${{ secrets.WAJO_BACKEND_CONTAINER_STAGING_NAME }}:${{ github.sha }}
        az containerapp update --name ${{ secrets.AZURE_ACA_STAGING_NAME }} \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --image $IMAGE_NAME

    - name: Update Celery Worker
      run: |
        IMAGE_NAME=${{ secrets.CONTAINER_REGISTRY_USERNAME }}.azurecr.io/${{ secrets.WAJO_BACKEND_CONTAINER_STAGING_NAME }}:${{ github.sha }}
        az containerapp update \
          --name wajo-celery-worker-staging \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --image $IMAGE_NAME \
          --command "celery" \
          --args "-A wajo_backend worker --loglevel=INFO"


    - name: Update Celery Beat
      run: |
        IMAGE_NAME=${{ secrets.CONTAINER_REGISTRY_USERNAME }}.azurecr.io/${{ secrets.WAJO_BACKEND_CONTAINER_STAGING_NAME }}:${{ github.sha }}
        az containerapp update \
          --name wajo-celery-beat-staging \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --image $IMAGE_NAME \
          --command "celery" \
          --args "-A wajo_backend beat --loglevel=INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler"
        
    - name: Cleanup old Docker images
      run: |
        # Keep only the last 3 images and delete older ones
        PURGE_CMD="acr purge --filter '${{ secrets.WAJO_BACKEND_CONTAINER_STAGING_NAME }}:.*' --ago 0d --keep 3 --untagged"
        az acr run --cmd "$PURGE_CMD" --registry ${{ secrets.CONTAINER_REGISTRY_USERNAME }} /dev/null
