name: CI/CD
on:
  push:
    branches:
      - main
      - pilot

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3
        with:
          clean: false

      - name: Set Branch-Specific Docker Compose File
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            export DOCKER_COMPOSE_FILE="docker-compose.yml"
            export APP_ENV="main"
          elif [[ "${{ github.ref_name }}" == "pilot" ]]; then
            export DOCKER_COMPOSE_FILE="docker-compose.pilot.yml"
            export APP_ENV="pilot"
          else
            echo "Unsupported branch for deployment: ${{ github.ref_name }}"
            exit 1
          fi
        shell: bash

      - name: Stop Running Docker Containers
        run: docker-compose -f $DOCKER_COMPOSE_FILE down
        env:
          DOCKER_COMPOSE_FILE: ${{ env.DOCKER_COMPOSE_FILE }}

      - name: Deploy Docker Containers
        run: docker-compose -f $DOCKER_COMPOSE_FILE up -d --build
        env:
          DOCKER_COMPOSE_FILE: ${{ env.DOCKER_COMPOSE_FILE }}
          APP_ENV: ${{ env.APP_ENV }}
