name: CI/CD
on:
  push:
    branches:
      - main
      - pilot

  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Set Branch-Specific Directory
        id: set-dir
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "DEPLOY_DIR=./deployments/wajo_main" >> $GITHUB_ENV
            echo "DOCKER_COMPOSE_FILE=docker-compose.yml" >> $GITHUB_ENV
            echo "PROJECT_NAME=wajo_main" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" == "pilot" ]]; then
            echo "DEPLOY_DIR=./deployments/wajo_pilot" >> $GITHUB_ENV
            echo "DOCKER_COMPOSE_FILE=docker-compose.pilot.yml" >> $GITHUB_ENV
            echo "PROJECT_NAME=wajo_pilot" >> $GITHUB_ENV
          else
            echo "Unsupported branch for deployment: ${{ github.ref_name }}"
            exit 1
          fi
        shell: bash

      - name: Create Deployment Directory
        run: mkdir -p ${{ env.DEPLOY_DIR }}

      - name: Sync Project Files to Deployment Directory
        uses: actions/checkout@v3
        with:
          clean: false
          path: ${{ env.DEPLOY_DIR }}

      - name: Stop Running Containers for Current Project
        run: docker-compose -f ${{ env.DOCKER_COMPOSE_FILE }} -p ${{ env.PROJECT_NAME }} down
        working-directory: ${{ env.DEPLOY_DIR }}

      - name: Deploy Containers for Current Project
        run: docker-compose -f ${{ env.DOCKER_COMPOSE_FILE }} -p ${{ env.PROJECT_NAME }} up -d --build
        working-directory: ${{ env.DEPLOY_DIR }}

